// File generated by 'npm run export'

import { SupportDefinition } from "./_types";

import supportAI from "./ai";
import supportAnim from "./anim";
import supportBoardBook from "./boards";
import supportSetupBook from "./setups";
import supportGraphics from "./graphics";
import supportInstruction from "./instructions";
import supportMeta from "./meta";
import supportPerformance from "./performance";
import supportFlow from "./flow";
import supportScripts from "./scripts";
import supportGenerators from "./generators";
import supportVariants from "./variants";

const supportDefinition: SupportDefinition = {
  AI: supportAI,
  anim: supportAnim,
  boards: supportBoardBook,
  setups: supportSetupBook,
  graphics: supportGraphics,
  instructions: supportInstruction,
  generators: supportGenerators,
  meta: supportMeta,
  performance: supportPerformance,
  flow: supportFlow,
  scripts: supportScripts,
  variants: supportVariants
};

export default supportDefinition;

export * from "./_types";
