// File generated by 'npm run export'

import { DuploDefinition } from "./_types";

import duploAI from "./ai";
import duploAnim from "./anim";
import duploBoardBook from "./boards";
import duploSetupBook from "./setups";
import duploGraphics from "./graphics";
import duploInstruction from "./instructions";
import duploMeta from "./meta";
import duploPerformance from "./performance";
import duploFlow from "./flow";
import duploScripts from "./scripts";
import duploGenerators from "./generators";
import duploVariantsBook from "./variants";

const duploDefinition: DuploDefinition = {
  AI: duploAI,
  anim: duploAnim,
  boards: duploBoardBook,
  setups: duploSetupBook,
  graphics: duploGraphics,
  instructions: duploInstruction,
  generators: duploGenerators,
  meta: duploMeta,
  performance: duploPerformance,
  flow: duploFlow,
  scripts: duploScripts,
  variants: duploVariantsBook
};

export default duploDefinition;

export * from "./_types";
