import { GameId } from "./_names";
import * as fs from "fs-extra";
import * as path from "path";

const out = path.join(__dirname, "../../dist/apis");

export async function exportGameAPI(gameId: GameId) {
  await fs.ensureDir(out);
  const me = path.join(out, gameId);
  await fs.emptyDir(me);
  await fs.writeFile(
    path.join(me, "static.ts"),
    `// Generated by "npm run exportGameAPIs"
import ${gameId} from "../../../../logic/dist/indiv/${gameId}";
import { makeStaticGameAPI } from "../../../src";

export const staticAPI = makeStaticGameAPI(${gameId});
export default staticAPI;
`
  );
  await fs.writeFile(
    path.join(me, "stateful.ts"),
    `// Generated by "npm run exportGameAPIs"
import ${gameId} from "../../../../logic/dist/indiv/${gameId}";
import { makeStatefulGameAPI } from "../../../src";

export const statefulAPI = makeStatefulGameAPI(${gameId});
export default statefulAPI;
`
  );
  console.log("Exporting api:s for", gameId);
}
