// File generated by 'npm run export'

import { RazzledazzleDefinition } from "./_types";

import razzledazzleAI from "./ai";
import razzledazzleAnim from "./anim";
import razzledazzleBoardBook from "./boards";
import razzledazzleSetupBook from "./setups";
import razzledazzleGraphics from "./graphics";
import razzledazzleInstruction from "./instructions";
import razzledazzleMeta from "./meta";
import razzledazzlePerformance from "./performance";
import razzledazzleFlow from "./flow";
import razzledazzleScripts from "./scripts";
import razzledazzleGenerators from "./generators";
import razzledazzleVariants from "./variants";

const razzledazzleDefinition: RazzledazzleDefinition = {
  AI: razzledazzleAI,
  anim: razzledazzleAnim,
  boards: razzledazzleBoardBook,
  setups: razzledazzleSetupBook,
  graphics: razzledazzleGraphics,
  instructions: razzledazzleInstruction,
  generators: razzledazzleGenerators,
  meta: razzledazzleMeta,
  performance: razzledazzlePerformance,
  flow: razzledazzleFlow,
  scripts: razzledazzleScripts,
  variants: razzledazzleVariants
};

export default razzledazzleDefinition;

export * from "./_types";
