import { AlgolEffect } from "./";
import { AlgolTestBlob } from "../../blob";

const tests: AlgolEffect<AlgolTestBlob>[] = [
  { moveat: ["mymark", { onlyin: "mylayer" }] },
  { setturnpos: ["myturnp", "mymark"] },
  { spawnat: ["mymark", "myunit"] },
  { spawnat: ["mymark", "myunit", 1] },
  {
    spawnat: [
      "mymark",
      "myunit",
      2,
      { foo: { read: ["mylayer", "mymark", "someProp"] } },
    ],
  },
  { spawnin: ["mylayer", "myunit"] },
  { spawnin: ["mylayer", "myunit", 1] },
  {
    spawnin: [
      "mylayer",
      "myunit",
      2,
      { foo: { read: ["mylayer", "mymark", "someProp"] } },
    ],
  },
  { setbattlevar: [{ playercase: ["mybattlev", "mybattlev"] }, 666] },
  { pushin: ["mylayer", { value: 3 }, { value: 2 }] },
  { pushin: ["mylayer", 3, 2] },
  { pushin: ["mylayer", 3] },
  { pushat: ["mymark", { value: 3 }, { value: 2 }] },
  { pushat: ["mymark", 3, 2] },
  { pushat: ["mymark", 3] },
  { killin: "mylayer" },
  { killid: { value: "someid" } },
  { moveat: ["mymark", { onlyin: "mylayer" }] },
  { forposin: ["mylayer", { killin: "mylayer" }] },
  { foridin: ["mylayer", { setid: [["loopid"], "group", "myunit"] }] },
  { killat: "mymark" },
  { stompat: ["mymark", "mymark"] },
  { stompid: [{ value: "someid" }, "mymark"] },
  { setat: ["mymark", "someprop", { turnvar: "myturnv" }] },
  { setin: ["mylayer", "someprop", { turnvar: "myturnv" }] },
  { setid: [["loopid"], "group", "myunit"] },
  { multi: [{ killat: "mymark" }, { stompat: ["mymark", "mymark"] }] },
  { morphat: ["mymark", { value: "myunit" }] },
  { morphin: ["mylayer", { value: "myunit" }] },
  { morphid: [{ value: "someid" }, { value: "myunit" }] },
  { adoptat: ["mymark", { value: 0 }] },
  { adoptat: ["mymark"] },
  { adoptin: ["mylayer", { value: ["player"] }] },
  { adoptid: [{ value: "someid" }, { value: ["otherplayer"] }] },
  { ifelse: [["true"], { killat: "mymark" }, { killat: "mymark" }] },
  { if: [["true"], { killat: "mymark" }] },
  { ifplayer: [1, { killat: "mymark" }] },
  { ifaction: ["mycmnd", { killat: "mymark" }] },
  { incbattlevar: ["mybattlev", 5] },
  { incbattlevar: ["mybattlev"] },
  { incturnvar: ["myturnv", 5] },
  { incturnvar: ["myturnv"] },
];
