import fs from "fs-extra";
import path from "path";
import prettier from "prettier";

const tagDir = path.join(__dirname, "../material/tags");
const allTags = fs.readdirSync(tagDir).filter(f => f != ".DS_Store");
const l = (d: string) => "n_" + d.replace(/-/g, "_");

// Item imports (tagList.ts)

const itemImports = allTags.map(
  d => `import { listing as ${l(d)} } from './tags/${d}/listing'`
);

const itemList = `// Generated by 'npm run listTag'

${itemImports.join("\n")}

export const tagList = [ ${allTags.map(l).join(", ")} ]`;

const tagListPath = path.join(__dirname, "../dist/tagList.ts");
fs.writeFileSync(
  tagListPath,
  prettier.format(itemList, { filepath: "foo.ts" })
);

// Full import (allTags.ts)

const fullImports = allTags.map(
  d => `import { tag as ${l(d)} } from './tags/${d}/tag'`
);

const fullList = `// Generated by 'npm run listTag'

${fullImports.join("\n")}

export const allTags = {
  ${allTags.map(nid => `'${nid}': ${l(nid)}`).join(",\n")}
}
`;

fs.writeFileSync(
  path.join(__dirname, "../dist/allTags.ts"),
  prettier.format(fullList, { filepath: "foo.ts" })
);
