import fs from "fs-extra";
import path from "path";
import prettier from "prettier";

const aboutDir = path.join(__dirname, "../material/about");
const allAbout = fs.readdirSync(aboutDir).filter(f => f != ".DS_Store");
const l = (d: string) => "n_" + d.replace(/-/g, "_");

// Item imports (aboutList.ts)

const itemImports = allAbout.map(
  d => `import { listing as ${l(d)} } from './about/${d}/listing'`
);

const itemList = `// Generated by 'npm run listAbout'

${itemImports.join("\n")}

export const aboutList = [ ${allAbout.map(l).join(", ")} ]`;

const aboutListPath = path.join(__dirname, "../dist/aboutList.ts");
fs.writeFileSync(
  aboutListPath,
  prettier.format(itemList, { filepath: "foo.ts" })
);

// Full import (allAbout.ts)

const fullImports = allAbout.map(
  d => `import { about as ${l(d)} } from './about/${d}/about'`
);

const fullList = `// Generated by 'npm run listAbout'

${fullImports.join("\n")}

export const allAbout = {
  ${allAbout.map(nid => `'${nid}': ${l(nid)}`).join(",\n")}
}
`;

fs.writeFileSync(
  path.join(__dirname, "../dist/allAbout.ts"),
  prettier.format(fullList, { filepath: "foo.ts" })
);
