import fs from "fs-extra";
import path from "path";
import prettier from "prettier";

const newsDir = path.join(__dirname, "../material/news");
const allNews = fs.readdirSync(newsDir).filter(f => f != ".DS_Store");

const l = (d: string) => "n_" + d.replace(/-/g, "_");

const imports = allNews.map(
  d => `import { listing as ${l(d)} } from './news/${d}/listing'`
);

const list = `// Generated by 'npm run listNews'

${imports.join("\n")}

export const newsList = [ ${allNews.map(l).join(", ")} ]`;

fs.writeFileSync(
  path.join(__dirname, "../dist/newsList.ts"),
  prettier.format(list, { filepath: "foo.ts" })
);
