// File generated by 'npm run export'

import { ChameleonDefinition } from "./_types";

import chameleonAI from "./ai";
import chameleonAnim from "./anim";
import chameleonBoardBook from "./boards";
import chameleonSetupBook from "./setups";
import chameleonGraphics from "./graphics";
import chameleonInstruction from "./instructions";
import chameleonMeta from "./meta";
import chameleonPerformance from "./performance";
import chameleonFlow from "./flow";
import chameleonScripts from "./scripts";
import chameleonGenerators from "./generators";

const chameleonDefinition: ChameleonDefinition = {
  AI: chameleonAI,
  anim: chameleonAnim,
  boards: chameleonBoardBook,
  setups: chameleonSetupBook,
  graphics: chameleonGraphics,
  instructions: chameleonInstruction,
  generators: chameleonGenerators,
  meta: chameleonMeta,
  performance: chameleonPerformance,
  flow: chameleonFlow,
  scripts: chameleonScripts,
};

export default chameleonDefinition;

export * from "./_types";
