// File generated by 'npm run export'

import { GekitaiDefinition } from "./_types";

import gekitaiAI from "./ai";
import gekitaiAnim from "./anim";
import gekitaiBoardBook from "./boards";
import gekitaiSetupBook from "./setups";
import gekitaiGraphics from "./graphics";
import gekitaiInstruction from "./instructions";
import gekitaiMeta from "./meta";
import gekitaiPerformance from "./performance";
import gekitaiFlow from "./flow";
import gekitaiScripts from "./scripts";
import gekitaiGenerators from "./generators";
import gekitaiVariantsBook from "./variants";

const gekitaiDefinition: GekitaiDefinition = {
  AI: gekitaiAI,
  anim: gekitaiAnim,
  boards: gekitaiBoardBook,
  setups: gekitaiSetupBook,
  graphics: gekitaiGraphics,
  instructions: gekitaiInstruction,
  generators: gekitaiGenerators,
  meta: gekitaiMeta,
  performance: gekitaiPerformance,
  flow: gekitaiFlow,
  scripts: gekitaiScripts,
  variants: gekitaiVariantsBook
};

export default gekitaiDefinition;

export * from "./_types";
