// File generated by 'npm run export'

import { FullDef } from '../../../types';
import { ShoveoffArtifactLayer, ShoveoffCommand, ShoveoffGenerator, ShoveoffLayer, ShoveoffMark, ShoveoffPhase, ShoveoffTerrain, ShoveoffUnit } from './_types';

import shoveoffAI from './ai';
import shoveoffBoard from './board';
import shoveoffSetup from './setup';
import shoveoffGraphics from './graphics';
import shoveoffInstruction from './instructions';
import shoveoffMeta from './meta';
import shoveoffFlow from './flow';
import shoveoffScripts from './scripts';
import shoveoffGenerators from './generators';

const shoveoffFullDef: FullDef<ShoveoffArtifactLayer, ShoveoffCommand, ShoveoffGenerator, ShoveoffLayer, ShoveoffMark, ShoveoffPhase, ShoveoffTerrain, ShoveoffUnit> = {
  AI: shoveoffAI,
  board: shoveoffBoard,
  setup: shoveoffSetup,
  graphics: shoveoffGraphics,
  instructions: shoveoffInstruction,
  generators: shoveoffGenerators,
  meta: shoveoffMeta,
  flow: shoveoffFlow,
  scripts: shoveoffScripts,
};

export default shoveoffFullDef;

export * from './_types';
