// File generated by 'npm run export'

import { FullDef } from '../../../types';
import { AmazonsLayer, AmazonsMark, AmazonsCommand, AmazonsTurnPos, AmazonsTurnVar, AmazonsBattlePos, AmazonsBattleVar, AmazonsArtifactLayer, AmazonsGenerator, AmazonsPhase, AmazonsTerrain, AmazonsUnit } from './_types';

import amazonsAI from './ai';
import amazonsBoard from './board';
import amazonsSetup from './setup';
import amazonsGraphics from './graphics';
import amazonsInstruction from './instructions';
import amazonsMeta from './meta';
import amazonsFlow from './flow';
import amazonsScripts from './scripts';
import amazonsGenerators from './generators';

const amazonsFullDef: FullDef<AmazonsLayer, AmazonsMark, AmazonsCommand, AmazonsTurnPos, AmazonsTurnVar, AmazonsBattlePos, AmazonsBattleVar, AmazonsArtifactLayer, AmazonsGenerator, AmazonsPhase, AmazonsTerrain, AmazonsUnit> = {
  AI: amazonsAI,
  board: amazonsBoard,
  setup: amazonsSetup,
  graphics: amazonsGraphics,
  instructions: amazonsInstruction,
  generators: amazonsGenerators,
  meta: amazonsMeta,
  flow: amazonsFlow,
  scripts: amazonsScripts,
};

export default amazonsFullDef;

export * from './_types';
