// File generated by 'npm run export'

import { TowersDefinition } from "./_types";

import towersAI from "./ai";
import towersAnim from "./anim";
import towersBoardBook from "./boards";
import towersSetupBook from "./setups";
import towersGraphics from "./graphics";
import towersInstruction from "./instructions";
import towersMeta from "./meta";
import towersPerformance from "./performance";
import towersFlow from "./flow";
import towersScripts from "./scripts";
import towersGenerators from "./generators";
import towersVariants from "./variants";

const towersDefinition: TowersDefinition = {
  AI: towersAI,
  anim: towersAnim,
  boards: towersBoardBook,
  setups: towersSetupBook,
  graphics: towersGraphics,
  instructions: towersInstruction,
  generators: towersGenerators,
  meta: towersMeta,
  performance: towersPerformance,
  flow: towersFlow,
  scripts: towersScripts,
  variants: towersVariants
};

export default towersDefinition;

export * from "./_types";
