// File generated by 'npm run export'

import { TunnelerDefinition } from "./_types";

import tunnelerAI from "./ai";
import tunnelerAnim from "./anim";
import tunnelerBoardBook from "./boards";
import tunnelerSetupBook from "./setups";
import tunnelerGraphics from "./graphics";
import tunnelerInstruction from "./instructions";
import tunnelerMeta from "./meta";
import tunnelerPerformance from "./performance";
import tunnelerFlow from "./flow";
import tunnelerScripts from "./scripts";
import tunnelerGenerators from "./generators";
import tunnelerVariants from "./variants";

const tunnelerDefinition: TunnelerDefinition = {
  AI: tunnelerAI,
  anim: tunnelerAnim,
  boards: tunnelerBoardBook,
  setups: tunnelerSetupBook,
  graphics: tunnelerGraphics,
  instructions: tunnelerInstruction,
  generators: tunnelerGenerators,
  meta: tunnelerMeta,
  performance: tunnelerPerformance,
  flow: tunnelerFlow,
  scripts: tunnelerScripts,
  variants: tunnelerVariants
};

export default tunnelerDefinition;

export * from "./_types";
