// File generated by 'npm run export'

import { GrensholmDefinition } from "./_types";

import grensholmAI from "./ai";
import grensholmAnim from "./anim";
import grensholmBoardBook from "./boards";
import grensholmSetupBook from "./setups";
import grensholmGraphics from "./graphics";
import grensholmInstruction from "./instructions";
import grensholmMeta from "./meta";
import grensholmPerformance from "./performance";
import grensholmFlow from "./flow";
import grensholmScripts from "./scripts";
import grensholmGenerators from "./generators";
import grensholmVariants from "./variants";

const grensholmDefinition: GrensholmDefinition = {
  AI: grensholmAI,
  anim: grensholmAnim,
  boards: grensholmBoardBook,
  setups: grensholmSetupBook,
  graphics: grensholmGraphics,
  instructions: grensholmInstruction,
  generators: grensholmGenerators,
  meta: grensholmMeta,
  performance: grensholmPerformance,
  flow: grensholmFlow,
  scripts: grensholmScripts,
  variants: grensholmVariants
};

export default grensholmDefinition;

export * from "./_types";
