import * as fs from "fs-extra";
import * as path from "path";

import { typeSignature } from "./types";

const defs = path.join(__dirname, "definitions");
const out = path.join(__dirname, "dist");

fs.removeSync(out);
fs.ensureDirSync(out);
fs.ensureDirSync(path.join(out, "games"));

const gameIds = fs.readdirSync(defs).filter(gid => gid !== ".DS_Store");

fs.writeFileSync(
  path.join(out, "list.ts"),
  `const list = [${gameIds.map(gid => `"${gid}"`).join(", ")}];
export default list;
`
);

const gpath = path.join(out, "games");
fs.ensureDirSync(gpath);
gameIds.forEach(gid => {
  const signature = typeSignature("FullDef", gid);
  fs.writeFileSync(
    path.join(gpath, gid + ".ts"),
    `// File generated by 'npm run export'

import { FullDef } from '../../types';
import { ${signature} } from '../../definitions/${gid}/_types';

import ${gid}AI from '../../definitions/${gid}/ai';
import ${gid}Board from '../../definitions/${gid}/board';
import ${gid}Setup from '../../definitions/${gid}/setup';
import ${gid}Graphics from '../../definitions/${gid}/graphics';
import ${gid}Instruction from '../../definitions/${gid}/instructions';
import ${gid}Meta from '../../definitions/${gid}/meta';
import ${gid}Rules from '../../definitions/${gid}/rules';
import ${gid}Scripts from '../../definitions/${gid}/scripts';

const ${gid}FullDef: FullDef<${signature}> = {
  AI: ${gid}AI,
  board: ${gid}Board,
  setup: ${gid}Setup,
  graphics: ${gid}Graphics,
  instructions: ${gid}Instruction,
  meta: ${gid}Meta,
  rules: ${gid}Rules,
  scripts: ${gid}Scripts,
};

export default ${gid}FullDef;

export * from '../../definitions/${gid}/_types';
`
  );
});

fs.writeFileSync(
  path.join(out, "lib.ts"),
  `${gameIds.map(gid => `import ${gid} from './games/${gid}';`).join("\n")}

const lib = {
${gameIds.map(gid => `  ${gid},\n`).join("")}};

export default lib;
`
);
