// File generated by 'npm run export'

import { FullDef } from '../../../types';
import { UglyduckLayer, UglyduckMark, UglyduckCommand, UglyduckTurnPos, UglyduckTurnVar, UglyduckBattlePos, UglyduckBattleVar, UglyduckArtifactLayer, UglyduckGenerator, UglyduckPhase, UglyduckTerrain, UglyduckUnit } from './_types';

import uglyduckAI from './ai';
import uglyduckBoard from './board';
import uglyduckSetup from './setup';
import uglyduckGraphics from './graphics';
import uglyduckInstruction from './instructions';
import uglyduckMeta from './meta';
import uglyduckFlow from './flow';
import uglyduckScripts from './scripts';
import uglyduckGenerators from './generators';

const uglyduckFullDef: FullDef<UglyduckLayer, UglyduckMark, UglyduckCommand, UglyduckTurnPos, UglyduckTurnVar, UglyduckBattlePos, UglyduckBattleVar, UglyduckArtifactLayer, UglyduckGenerator, UglyduckPhase, UglyduckTerrain, UglyduckUnit> = {
  AI: uglyduckAI,
  board: uglyduckBoard,
  setup: uglyduckSetup,
  graphics: uglyduckGraphics,
  instructions: uglyduckInstruction,
  generators: uglyduckGenerators,
  meta: uglyduckMeta,
  flow: uglyduckFlow,
  scripts: uglyduckScripts,
};

export default uglyduckFullDef;

export * from './_types';
