// File generated by 'npm run export'

import { FullDef } from '../../../types';
import { JostleLayer, JostleMark, JostleCommand, JostleTurnPos, JostleTurnVar, JostleBattlePos, JostleBattleVar, JostleArtifactLayer, JostleGenerator, JostlePhase, JostleTerrain, JostleUnit } from './_types';

import jostleAI from './ai';
import jostleBoard from './board';
import jostleSetup from './setup';
import jostleGraphics from './graphics';
import jostleInstruction from './instructions';
import jostleMeta from './meta';
import jostleFlow from './flow';
import jostleScripts from './scripts';
import jostleGenerators from './generators';

const jostleFullDef: FullDef<JostleLayer, JostleMark, JostleCommand, JostleTurnPos, JostleTurnVar, JostleBattlePos, JostleBattleVar, JostleArtifactLayer, JostleGenerator, JostlePhase, JostleTerrain, JostleUnit> = {
  AI: jostleAI,
  board: jostleBoard,
  setup: jostleSetup,
  graphics: jostleGraphics,
  instructions: jostleInstruction,
  generators: jostleGenerators,
  meta: jostleMeta,
  flow: jostleFlow,
  scripts: jostleScripts,
};

export default jostleFullDef;

export * from './_types';
