// File generated by 'npm run export'

import { JostleDefinition } from './_types';

import jostleAI from './ai';
import jostleBoard from './board';
import jostleSetup from './setup';
import jostleGraphics from './graphics';
import jostleInstruction from './instructions';
import jostleMeta from './meta';
import jostlePerformance from './performance';
import jostleFlow from './flow';
import jostleScripts from './scripts';
import jostleGenerators from './generators';

const jostleDefinition: JostleDefinition = {
  AI: jostleAI,
  board: jostleBoard,
  setup: jostleSetup,
  graphics: jostleGraphics,
  instructions: jostleInstruction,
  generators: jostleGenerators,
  meta: jostleMeta,
  performance: jostlePerformance,
  flow: jostleFlow,
  scripts: jostleScripts,
};

export default jostleDefinition;

export * from './_types';
