// File generated by 'npm run export'

import { FullDef } from '../../types';
import { KickrunArtifactLayer, KickrunCommand, KickrunGenerator, KickrunLayer, KickrunMark, KickrunPhase, KickrunTerrain, KickrunUnit } from './_types';

import kickrunAI from './ai';
import kickrunBoard from './board';
import kickrunSetup from './setup';
import kickrunGraphics from './graphics';
import kickrunInstruction from './instructions';
import kickrunMeta from './meta';
import kickrunFlow from './flow';
import kickrunScripts from './scripts';
import kickrunGenerators from './generators';

const kickrunFullDef: FullDef<KickrunArtifactLayer, KickrunCommand, KickrunGenerator, KickrunLayer, KickrunMark, KickrunPhase, KickrunTerrain, KickrunUnit> = {
  AI: kickrunAI,
  board: kickrunBoard,
  setup: kickrunSetup,
  graphics: kickrunGraphics,
  instructions: kickrunInstruction,
  generators: kickrunGenerators,
  meta: kickrunMeta,
  flow: kickrunFlow,
  scripts: kickrunScripts,
};

export default kickrunFullDef;

export * from './_types';
