// File generated by 'npm run export'

import { SaposDefinition } from "./_types";

import saposAI from "./ai";
import saposAnim from "./anim";
import saposBoardBook from "./boards";
import saposSetupBook from "./setups";
import saposGraphics from "./graphics";
import saposInstruction from "./instructions";
import saposMeta from "./meta";
import saposPerformance from "./performance";
import saposFlow from "./flow";
import saposScripts from "./scripts";
import saposGenerators from "./generators";
import saposVariants from "./variants";

const saposDefinition: SaposDefinition = {
  AI: saposAI,
  anim: saposAnim,
  boards: saposBoardBook,
  setups: saposSetupBook,
  graphics: saposGraphics,
  instructions: saposInstruction,
  generators: saposGenerators,
  meta: saposMeta,
  performance: saposPerformance,
  flow: saposFlow,
  scripts: saposScripts,
  variants: saposVariants
};

export default saposDefinition;

export * from "./_types";
