// File generated by 'npm run export'

import { NeutreekoDefinition } from "./_types";

import neutreekoAI from "./ai";
import neutreekoAnim from "./anim";
import neutreekoBoardBook from "./boards";
import neutreekoSetupBook from "./setups";
import neutreekoGraphics from "./graphics";
import neutreekoInstruction from "./instructions";
import neutreekoMeta from "./meta";
import neutreekoPerformance from "./performance";
import neutreekoFlow from "./flow";
import neutreekoScripts from "./scripts";
import neutreekoGenerators from "./generators";
import neutreekoVariants from "./variants";

const neutreekoDefinition: NeutreekoDefinition = {
  AI: neutreekoAI,
  anim: neutreekoAnim,
  boards: neutreekoBoardBook,
  setups: neutreekoSetupBook,
  graphics: neutreekoGraphics,
  instructions: neutreekoInstruction,
  generators: neutreekoGenerators,
  meta: neutreekoMeta,
  performance: neutreekoPerformance,
  flow: neutreekoFlow,
  scripts: neutreekoScripts,
  variants: neutreekoVariants
};

export default neutreekoDefinition;

export * from "./_types";
