// File generated by 'npm run export'

import { FullDef } from '../../../types';
import { _testArtifactLayer, _testCommand, _testGenerator, _testLayer, _testMark, _testPhase, _testTerrain, _testUnit } from './_types';

import _testAI from './ai';
import _testBoard from './board';
import _testSetup from './setup';
import _testGraphics from './graphics';
import _testInstruction from './instructions';
import _testMeta from './meta';
import _testFlow from './flow';
import _testScripts from './scripts';
import _testGenerators from './generators';

const _testFullDef: FullDef<_testArtifactLayer, _testCommand, _testGenerator, _testLayer, _testMark, _testPhase, _testTerrain, _testUnit> = {
  AI: _testAI,
  board: _testBoard,
  setup: _testSetup,
  graphics: _testGraphics,
  instructions: _testInstruction,
  generators: _testGenerators,
  meta: _testMeta,
  flow: _testFlow,
  scripts: _testScripts,
};

export default _testFullDef;

export * from './_types';
