// File generated by 'npm run export'

import { FullDef } from '../../../types';
import { MurusgallicusArtifactLayer, MurusgallicusCommand, MurusgallicusGenerator, MurusgallicusLayer, MurusgallicusMark, MurusgallicusPhase, MurusgallicusTerrain, MurusgallicusUnit } from './_types';

import murusgallicusAI from './ai';
import murusgallicusBoard from './board';
import murusgallicusSetup from './setup';
import murusgallicusGraphics from './graphics';
import murusgallicusInstruction from './instructions';
import murusgallicusMeta from './meta';
import murusgallicusFlow from './flow';
import murusgallicusScripts from './scripts';
import murusgallicusGenerators from './generators';

const murusgallicusFullDef: FullDef<MurusgallicusArtifactLayer, MurusgallicusCommand, MurusgallicusGenerator, MurusgallicusLayer, MurusgallicusMark, MurusgallicusPhase, MurusgallicusTerrain, MurusgallicusUnit> = {
  AI: murusgallicusAI,
  board: murusgallicusBoard,
  setup: murusgallicusSetup,
  graphics: murusgallicusGraphics,
  instructions: murusgallicusInstruction,
  generators: murusgallicusGenerators,
  meta: murusgallicusMeta,
  flow: murusgallicusFlow,
  scripts: murusgallicusScripts,
};

export default murusgallicusFullDef;

export * from './_types';
