const fs = require("fs-extra");
const path = require("path");

const payloadFolder = path.join(__dirname, "../../dist/payloads");

module.exports = gameId => {
  const content = `
// Generated by the makeGamePayload command

import api from "../../../../battle/dist/apis/${gameId}/static";
import graphics from "../../../../graphics/dist/svgDataURIs/${gameId}";
import meta from "../../../../games/dist/meta/${gameId}";
import demo from "../../../../battle/dist/demos/${gameId}";
import { rules } from "../../../../content/dist/games/${gameId}/rules";
import { preloads } from "../../../../content/dist/games/${gameId}/preloads";
import { AlgolGamePayload } from "../../../../types";

export const payload: AlgolGamePayload = {
  api,
  graphics,
  meta,
  demo,
  rules,
  imgsToPreload: preloads
};
export default payload;
`;
  const outFolder = path.join(payloadFolder, gameId);
  fs.ensureDirSync(outFolder);
  const out = path.join(outFolder, "index.ts");
  fs.writeFileSync(out, content);
  console.log("Made payload for", gameId);
};
