// File generated by 'npm run export'

import { MurusgallicusadvancedDefinition } from "./_types";

import murusgallicusadvancedAI from "./ai";
import murusgallicusadvancedAnim from "./anim";
import murusgallicusadvancedBoard from "./board";
import murusgallicusadvancedSetupBook from "./setups";
import murusgallicusadvancedGraphics from "./graphics";
import murusgallicusadvancedInstruction from "./instructions";
import murusgallicusadvancedMeta from "./meta";
import murusgallicusadvancedPerformance from "./performance";
import murusgallicusadvancedFlow from "./flow";
import murusgallicusadvancedScripts from "./scripts";
import murusgallicusadvancedGenerators from "./generators";

const murusgallicusadvancedDefinition: MurusgallicusadvancedDefinition = {
  AI: murusgallicusadvancedAI,
  anim: murusgallicusadvancedAnim,
  board: murusgallicusadvancedBoard,
  setups: murusgallicusadvancedSetupBook,
  graphics: murusgallicusadvancedGraphics,
  instructions: murusgallicusadvancedInstruction,
  generators: murusgallicusadvancedGenerators,
  meta: murusgallicusadvancedMeta,
  performance: murusgallicusadvancedPerformance,
  flow: murusgallicusadvancedFlow,
  scripts: murusgallicusadvancedScripts,
};

export default murusgallicusadvancedDefinition;

export * from "./_types";
