// File generated by 'npm run export'

import { ThreemusketeersDefinition } from "./_types";

import threemusketeersAI from "./ai";
import threemusketeersAnim from "./anim";
import threemusketeersBoardBook from "./boards";
import threemusketeersSetupBook from "./setups";
import threemusketeersGraphics from "./graphics";
import threemusketeersInstruction from "./instructions";
import threemusketeersMeta from "./meta";
import threemusketeersPerformance from "./performance";
import threemusketeersFlow from "./flow";
import threemusketeersScripts from "./scripts";
import threemusketeersGenerators from "./generators";
import threemusketeersVariantsBook from "./variants";

const threemusketeersDefinition: ThreemusketeersDefinition = {
  AI: threemusketeersAI,
  anim: threemusketeersAnim,
  boards: threemusketeersBoardBook,
  setups: threemusketeersSetupBook,
  graphics: threemusketeersGraphics,
  instructions: threemusketeersInstruction,
  generators: threemusketeersGenerators,
  meta: threemusketeersMeta,
  performance: threemusketeersPerformance,
  flow: threemusketeersFlow,
  scripts: threemusketeersScripts,
  variants: threemusketeersVariantsBook,
};

export default threemusketeersDefinition;

export * from "./_types";
