// File generated by 'npm run export'

import { ThreemusketeersDefinition } from './_types';

import threemusketeersAI from './ai';
import threemusketeersBoard from './board';
import threemusketeersSetup from './setup';
import threemusketeersGraphics from './graphics';
import threemusketeersInstruction from './instructions';
import threemusketeersMeta from './meta';
import threemusketeersPerformance from './performance';
import threemusketeersFlow from './flow';
import threemusketeersScripts from './scripts';
import threemusketeersGenerators from './generators';

const threemusketeersDefinition: ThreemusketeersDefinition = {
  AI: threemusketeersAI,
  board: threemusketeersBoard,
  setup: threemusketeersSetup,
  graphics: threemusketeersGraphics,
  instructions: threemusketeersInstruction,
  generators: threemusketeersGenerators,
  meta: threemusketeersMeta,
  performance: threemusketeersPerformance,
  flow: threemusketeersFlow,
  scripts: threemusketeersScripts,
};

export default threemusketeersDefinition;

export * from './_types';
