// File generated by 'npm run export'

import { AmbivalenteDefinition } from "./_types";

import ambivalenteAI from "./ai";
import ambivalenteAnim from "./anim";
import ambivalenteBoardBook from "./boards";
import ambivalenteSetupBook from "./setups";
import ambivalenteGraphics from "./graphics";
import ambivalenteInstruction from "./instructions";
import ambivalenteMeta from "./meta";
import ambivalentePerformance from "./performance";
import ambivalenteFlow from "./flow";
import ambivalenteScripts from "./scripts";
import ambivalenteGenerators from "./generators";
import ambivalenteVariants from "./variants";

const ambivalenteDefinition: AmbivalenteDefinition = {
  AI: ambivalenteAI,
  anim: ambivalenteAnim,
  boards: ambivalenteBoardBook,
  setups: ambivalenteSetupBook,
  graphics: ambivalenteGraphics,
  instructions: ambivalenteInstruction,
  generators: ambivalenteGenerators,
  meta: ambivalenteMeta,
  performance: ambivalentePerformance,
  flow: ambivalenteFlow,
  scripts: ambivalenteScripts,
  variants: ambivalenteVariants
};

export default ambivalenteDefinition;

export * from "./_types";
