// File generated by 'npm run export'

import { CanthesardinesDefinition } from "./_types";

import canthesardinesAI from "./ai";
import canthesardinesAnim from "./anim";
import canthesardinesBoardBook from "./boards";
import canthesardinesSetupBook from "./setups";
import canthesardinesGraphics from "./graphics";
import canthesardinesInstruction from "./instructions";
import canthesardinesMeta from "./meta";
import canthesardinesPerformance from "./performance";
import canthesardinesFlow from "./flow";
import canthesardinesScripts from "./scripts";
import canthesardinesGenerators from "./generators";
import canthesardinesVariants from "./variants";

const canthesardinesDefinition: CanthesardinesDefinition = {
  AI: canthesardinesAI,
  anim: canthesardinesAnim,
  boards: canthesardinesBoardBook,
  setups: canthesardinesSetupBook,
  graphics: canthesardinesGraphics,
  instructions: canthesardinesInstruction,
  generators: canthesardinesGenerators,
  meta: canthesardinesMeta,
  performance: canthesardinesPerformance,
  flow: canthesardinesFlow,
  scripts: canthesardinesScripts,
  variants: canthesardinesVariants
};

export default canthesardinesDefinition;

export * from "./_types";
