// File generated by 'npm run export'

import { AriesDefinition } from "./_types";

import ariesAI from "./ai";
import ariesAnim from "./anim";
import ariesBoardBook from "./boards";
import ariesSetupBook from "./setups";
import ariesGraphics from "./graphics";
import ariesInstruction from "./instructions";
import ariesMeta from "./meta";
import ariesPerformance from "./performance";
import ariesFlow from "./flow";
import ariesScripts from "./scripts";
import ariesGenerators from "./generators";
import ariesVariantsBook from "./variants";

const ariesDefinition: AriesDefinition = {
  AI: ariesAI,
  anim: ariesAnim,
  boards: ariesBoardBook,
  setups: ariesSetupBook,
  graphics: ariesGraphics,
  instructions: ariesInstruction,
  generators: ariesGenerators,
  meta: ariesMeta,
  performance: ariesPerformance,
  flow: ariesFlow,
  scripts: ariesScripts,
  variants: ariesVariantsBook,
};

export default ariesDefinition;

export * from "./_types";
