// File generated by 'npm run export'

import { AriesDefinition } from "./_types";

import ariesAI from "./ai";
import ariesAnim from "./anim";
import ariesBoard from "./board";
import ariesSetupBook from "./setups";
import ariesGraphics from "./graphics";
import ariesInstruction from "./instructions";
import ariesMeta from "./meta";
import ariesPerformance from "./performance";
import ariesFlow from "./flow";
import ariesScripts from "./scripts";
import ariesGenerators from "./generators";

const ariesDefinition: AriesDefinition = {
  AI: ariesAI,
  anim: ariesAnim,
  board: ariesBoard,
  setups: ariesSetupBook,
  graphics: ariesGraphics,
  instructions: ariesInstruction,
  generators: ariesGenerators,
  meta: ariesMeta,
  performance: ariesPerformance,
  flow: ariesFlow,
  scripts: ariesScripts,
};

export default ariesDefinition;

export * from "./_types";
