import prettier from "prettier";
import { punctuate } from "../../../common";
import { FullDefAnon } from "../../../types";

export const makeGameMainPage = (def: FullDefAnon) => {
  const gameId = def.meta.id;
  const content = `
// Generated by the makeGamePages command

import React from "react";

import payload from "../../../../payloads/dist/games/${gameId}";
import { GamePage } from "../../../../ui/src/components/GamePage";
import { AlgolPage } from "../../../../types";
import { makeGameNav } from "../../../../common/nav/makeGameNav";

export const Game: AlgolPage = props => {
  const { ctxt, actions } = props;
  return (
    <GamePage gamePayload={payload} actions={actions} ctxt={ctxt} />
  );
};

Game.domain = "${gameId}";
Game.mainImage = "/images/games/${gameId}/${gameId}_active.png"
Game.metaDesc = "Play the abstract board game ${
    def.meta.name
  } at Chessicals! ${punctuate(def.meta.tagline, "!")}"
Game.metaTitle = "${def.meta.name}${
    def.meta.author ? ` by ${def.meta.author}` : ""
  }"
Game.title = "${def.meta.name}"
Game.preloadImages = payload.imgsToPreload
Game.nav = makeGameNav(payload.meta)

export default Game;
`;
  return prettier.format(content, { filepath: "foo.ts" });
};
