import prettier from "prettier";
import { AlgolArticle, AlgolMeta, AlgolGameBlobAnon } from "../../../types";
import allMeta from "../../../games/dist/meta";

export const makeGameAboutPage = (article: AlgolArticle) => {
  const meta: AlgolMeta<AlgolGameBlobAnon> = allMeta[article.id];
  const content = `
// Generated by the makeGameAboutPage command

import article from "../../../../../payloads/dist/articles/gamesAbout/${meta.id}";
import meta from "../../../../../games/dist/meta/${meta.id}";
import { makePayloadArticlePage } from "../../../../../ui/src/components/PayloadArticlePage";
import { makeGameAboutNav } from "../../../../../common/nav/makeGameAboutNav";

export const AboutGamePage = makePayloadArticlePage(article);

const nav = makeGameAboutNav(meta);
AboutGamePage.nav = nav
AboutGamePage.title = nav.me.title
AboutGamePage.metaDesc = nav.me.desc
AboutGamePage.mainImage = article.mainImage;

export default AboutGamePage;
`;
  return prettier.format(content, { filepath: "foo.ts" });
};
