import prettier from "prettier";
import { AlgolArticle, AlgolMeta, AlgolGameBlobAnon } from "../../../types";
import allMeta from "../../../games/dist/meta";

export const makeGameRulesPage = (article: AlgolArticle) => {
  const meta: AlgolMeta<AlgolGameBlobAnon> = allMeta[article.id];
  const content = `
// Generated by the makeGameRulesPage command

import React, { Fragment } from "react";

import Head from "next/head";
import { PayloadArticlePage } from "../../../../../ui/src/components/PayloadArticlePage";
import { AlgolPage } from "../../../../../ui/src/helpers/algolPage";
import article from "../../../../../payloads/dist/articles/gamesRules/${meta.id}";

export const GameRulePage: AlgolPage = props => {
  const crumbs = [
    { content: "Games", url: "/games" },
    { content: "${meta.name}", url: "/games/${meta.slug}" },
    { content: "Rules" }
  ];
  return (
    <Fragment>
      <Head>
        <meta property="og:image" content={article.mainImage} />
        <meta property="og:title" content={article.title} />
        <meta property="og:description" content={article.blurb} />
        <title>{article.title}</title>
      </Head>
      <PayloadArticlePage
        crumbs={crumbs}
        article={article}
        actions={props.actions}
      />
    </Fragment>
  );
};

export default GameRulePage;
`;
  return prettier.format(content, { filepath: "foo.ts" });
};
