import prettier from "prettier";
import { gameSlug } from "../../../common";
import { FullDefAnon } from "../../../types";

export const makeGameAboutPage = (def: FullDefAnon) => {
  const gameId = def.meta.id;
  const content = `
// Generated by the makeGamePages command

import React, { Fragment } from "react";

import Head from "next/head";
import { ArticlePage } from "../../../../ui/src/components/ArticlePage";
import { pageActions } from "../../../helpers";
import { about } from "../../../../content/dist/games/${gameId}/about";

export const Game = () => {
  const crumbs = [
    { content: "Games", url: "/games" },
    { content: "${def.meta.name}", url: "/games/${gameSlug(def.meta)}" },
    { content: "About" }
  ];
  return (
    <Fragment>
      <Head>
        <meta property="og:site_name" content="Chessicals"/>
        <meta property="og:image" content="/images/games/${gameId}/${gameId}_${
    def.variants[0].code
  }_active.png"/>
        <meta property="og:title" content="About ${def.meta.name}"/>
        <meta property="og:description" content="More information about ${
          def.meta.name
        }"/>
        <title>About ${def.meta.name}</title>
      </Head>
      <ArticlePage
        crumbs={crumbs}
        title="About ${def.meta.name}"
        actions={pageActions}
        html={about.html}
      />
    </Fragment>
  );
};

export default Game;
`;
  return prettier.format(content, { filepath: "foo.ts" });
};
