import prettier from "prettier";
import { AlgolArticle, AlgolMeta, AlgolGameBlobAnon } from "../../../types";
import allMeta from "../../../games/dist/meta";

export const makeGameRulesPage = (article: AlgolArticle) => {
  const meta: AlgolMeta<AlgolGameBlobAnon> = allMeta[article.id];
  const content = `
// Generated by the makeGameRulesPage command

import article from "../../../../../payloads/dist/articles/gamesRules/${meta.id}";
import meta from "../../../../../games/dist/meta/${meta.id}";
import { makePayloadArticlePage } from "../../../../../ui/src/components/PayloadArticlePage";
import { makeGameRulesNav } from "../../../../../common/nav/makeGameRulesNav";

export const GameRulePage = makePayloadArticlePage(article);

const nav = makeGameRulesNav(meta);
GameRulePage.nav = nav
GameRulePage.title = nav.me.title
GameRulePage.metaDesc = nav.me.desc
GameRulePage.mainImage = article.mainImage;

export default GameRulePage;
`;
  return prettier.format(content, { filepath: "foo.ts" });
};
