import fs from "fs-extra";
import path from "path";
import prettier from "prettier";
import { AlgolArticle } from "../../../types";

const aboutFolder = path.join(__dirname, "../../pages/about");

export const makeAboutPage = (article: AlgolArticle) => {
  const content = `
  // Generated by the makeAboutPage command

  import article from "../../../../payloads/dist/articles/about/${article.id}";
  import { makePayloadArticlePage } from "../../../../ui/src/components/PayloadArticlePage";
  import { makeAboutArticleNav } from "../../../../common/nav/makeAboutArticleNav";
  
  export const AboutArticle = makePayloadArticlePage(article);
  
  AboutArticle.mainImage = article.mainImage;
  AboutArticle.title = article.title;
  AboutArticle.metaDesc = article.blurb;
  AboutArticle.nav = makeAboutArticleNav(article);
  
  export default AboutArticle;
  `;
  const out = path.join(aboutFolder, article.slug);
  fs.emptyDirSync(out);
  fs.writeFileSync(
    path.join(out, "index.tsx"),
    prettier.format(content, { filepath: "foo.ts" })
  );
  console.log("Made about page for", article.id);
};
