import fs from "fs-extra";
import path from "path";
import prettier from "prettier";
import { AlgolArticle } from "../../../types";

const tagFolder = path.join(__dirname, "../../pages/tags");

export const makeTagPage = (article: AlgolArticle) => {
  const content = `
  // Generated by the makeTagPage command
  
  import React, { Fragment } from "react";
  
  import Head from "next/head";
  import { PayloadArticlePage } from "../../../../ui/src/components/PayloadArticlePage";
  import { pageActions } from "../../../helpers";
  import article from "../../../../payloads/dist/articles/tags/${article.id}";
  
  export const Article = () => {
    const crumbs = [{ content: "Tags", url: "/tags" }, { content: article.title }];
    return (
      <Fragment>
        <Head>
          <meta property="og:site_name" content="Chessicals"/>
          <meta property="og:image" content={article.mainImage} />
          <meta property="og:title" content={article.title} />
          <meta property="og:description" content={article.blurb}/>
          <title>{article.title}</title>
        </Head>
        <PayloadArticlePage
          crumbs={crumbs}
          article={article}
          actions={pageActions}
        />
      </Fragment>
    );
  };
  
  export default Article;
  `;
  const out = path.join(tagFolder, article.slug);
  fs.emptyDirSync(out);
  fs.writeFileSync(
    path.join(out, "index.tsx"),
    prettier.format(content, { filepath: "foo.ts" })
  );
  console.log("Made tag page for", article.id);
};
