import fs from "fs-extra";
import path from "path";
import prettier from "prettier";
import { AlgolArticleData } from "../../../types";

const aboutFolder = path.join(__dirname, "../../pages/about");

export const makeAboutPage = (data: AlgolArticleData) => {
  const content = `
  // Generated by the makeAboutPages command
  
  import React, { Fragment } from "react";
  
  import Head from "next/head";
  import { ArticlePage } from "../../../../ui/src/components/ArticlePage";
  import { pageActions } from "../../../helpers";
  import { about } from "../../../../content/dist/about/${data.id}/about";
  
  export const Article = () => {
    const title = \`${data.title}\`;
    const crumbs = [{ content: "About", url: "/about" }, { content: "${data.title}" }];
    return (
      <Fragment>
        <Head>
          <meta property="og:site_name" content="Chessicals"/>
          <meta property="og:image" content="${data.mainImage}" />
          <meta property="og:title" content={title} />
          <meta property="og:description" content="${data.blurb}"/>
          <title>{title}</title>
        </Head>
        <ArticlePage
          crumbs={crumbs}
          title={title}
          actions={pageActions}
          html={about}
        />
      </Fragment>
    );
  };
  
  export default Article;
  `;
  const out = path.join(aboutFolder, data.slug);
  fs.emptyDirSync(out);
  fs.writeFileSync(
    path.join(out, "index.tsx"),
    prettier.format(content, { filepath: "foo.ts" })
  );
  console.log("Made about page for", data.id);
};
