import fs from "fs-extra";
import path from "path";
import prettier from "prettier";
import { AlgolArticle } from "../../../types";

const newsFolder = path.join(__dirname, "../../pages/news");

export const makeNewsPage = (article: AlgolArticle) => {
  const content = `
  // Generated by the makeNewsPage command
  
  import article from "../../../../payloads/dist/articles/news/${article.id}";
  import { makePayloadArticlePage } from "../../../../ui/src/components/PayloadArticlePage";
  import { makeNewsArticleNav } from "../../../../common/nav/makeNewsArticleNav";

  export const NewsArticle = makePayloadArticlePage(article);

  NewsArticle.mainImage = article.mainImage;
  NewsArticle.title = article.title;
  NewsArticle.metaDesc = article.blurb;
  NewsArticle.nav = makeNewsArticleNav(article);

  export default NewsArticle;
  `;
  const out = path.join(newsFolder, article.slug);
  fs.emptyDirSync(out);
  fs.writeFileSync(
    path.join(out, "index.tsx"),
    prettier.format(content, { filepath: "foo.ts" })
  );
  console.log("Made news page for", article.id);
};
