import prettier from "prettier";
import { AlgolArticle, AlgolMeta, AlgolGameBlobAnon } from "../../../types";
import allMeta from "../../../games/dist/meta";

export const makeGameAboutPage = (article: AlgolArticle) => {
  const meta: AlgolMeta<AlgolGameBlobAnon> = allMeta[article.id];
  const content = `
// Generated by the makeGameAboutPage command

import React from "react";

import { PayloadArticlePage } from "../../../../../ui/src/components/PayloadArticlePage";
import { AlgolPage } from "../../../../../ui/src/helpers/algolPage";
import article from "../../../../../payloads/dist/articles/gamesAbout/${meta.id}";

export const AboutGamePage: AlgolPage = props => {
  const crumbs = [
    { content: "Games", url: "/games" },
    { content: "${meta.name}", url: "/games/${meta.slug}" },
    { content: "About" }
  ];
  return (
    <PayloadArticlePage
      crumbs={crumbs}
      article={article}
      actions={props.actions}
    />
  );
};

AboutGamePage.mainImage = article.mainImage
AboutGamePage.title = article.title
AboutGamePage.metaDesc = article.blurb

export default AboutGamePage;
`;
  return prettier.format(content, { filepath: "foo.ts" });
};
