import prettier from "prettier";
import { punctuate } from "../../../common";
import { FullDefAnon } from "../../../types";

export const makeGameMainPage = (def: FullDefAnon) => {
  const gameId = def.meta.id;
  const metaDesc = `Play the abstract board game ${
    def.meta.name
  } at Chessicals! ${punctuate(def.meta.tagline)}`;
  const content = `
// Generated by the makeGamePages command

import React, { Fragment, useMemo } from "react";

import Head from "next/head";
import payload from "../../../../payloads/dist/games/${gameId}";
import { GamePage } from "../../../../ui/src/components/GamePage";
import { pageActions, useBattleNavActions } from "../../../helpers";

export const Game = () => {
  const preloadTags = payload.imgsToPreload.map(url => <link key={url} rel="preload" as="image" href={url} /> )
  const [mode, sessionId, battleNavActions] = useBattleNavActions();
  const actions = useMemo(() => ({ ...pageActions, ...battleNavActions }), [
    battleNavActions,
  ]);
  const ctxt = useMemo(() => ({ sessionId, mode }), [sessionId, mode]);
  return (
    <Fragment>
      <Head>
        <meta property="og:image" content="/images/games/${gameId}/${gameId}_${def.variants[0].code}_active.png"/>
        <meta property="og:title" content="Play ${def.meta.name} online"/>
        <meta property="og:description" content="${metaDesc}"/>
        <title>${def.meta.name}</title>
        {preloadTags}
      </Head>
      <GamePage gamePayload={payload} actions={actions} ctxt={ctxt} />
    </Fragment>
  );
};

export default Game;
`;
  return prettier.format(content, { filepath: "foo.ts" });
};
