const fs = require("fs-extra");
const path = require("path");

const list = require("../../games/dist/gameList");

const payloadsFolder = path.join(__dirname, "../dist/payloads");

const code = `// Generated by the exportAllGamePayloads command
${list.map(gameId => `import ${gameId} from './${gameId}';`).join("\n")}

export const allPayloads = {
${list.map(gameId => `  ${gameId},`).join("\n")}
};

export default allPayloads;
`;

fs.ensureDirSync(payloadsFolder);
fs.writeFileSync(path.join(payloadsFolder, "index.ts"), code);
