// File generated by 'npm run export'

import { KingsvalleyDefinition } from "./_types";

import kingsvalleyAI from "./ai";
import kingsvalleyAnim from "./anim";
import kingsvalleyBoardBook from "./boards";
import kingsvalleySetupBook from "./setups";
import kingsvalleyGraphics from "./graphics";
import kingsvalleyInstruction from "./instructions";
import kingsvalleyMeta from "./meta";
import kingsvalleyPerformance from "./performance";
import kingsvalleyFlow from "./flow";
import kingsvalleyScripts from "./scripts";
import kingsvalleyGenerators from "./generators";
import kingsvalleyVariants from "./variants";

const kingsvalleyDefinition: KingsvalleyDefinition = {
  AI: kingsvalleyAI,
  anim: kingsvalleyAnim,
  boards: kingsvalleyBoardBook,
  setups: kingsvalleySetupBook,
  graphics: kingsvalleyGraphics,
  instructions: kingsvalleyInstruction,
  generators: kingsvalleyGenerators,
  meta: kingsvalleyMeta,
  performance: kingsvalleyPerformance,
  flow: kingsvalleyFlow,
  scripts: kingsvalleyScripts,
  variants: kingsvalleyVariants
};

export default kingsvalleyDefinition;

export * from "./_types";
