// File generated by 'npm run export'

import { FullDef } from '../../types';
import { DuploArtifactLayer, DuploCommand, DuploGenerator, DuploLayer, DuploMark, DuploPhase, DuploTerrain, DuploUnit } from './_types';

import duploAI from './ai';
import duploBoard from './board';
import duploSetup from './setup';
import duploGraphics from './graphics';
import duploInstruction from './instructions';
import duploMeta from './meta';
import duploFlow from './flow';
import duploScripts from './scripts';
import duploGenerators from './generators';

const duploFullDef: FullDef<DuploArtifactLayer, DuploCommand, DuploGenerator, DuploLayer, DuploMark, DuploPhase, DuploTerrain, DuploUnit> = {
  AI: duploAI,
  board: duploBoard,
  setup: duploSetup,
  graphics: duploGraphics,
  instructions: duploInstruction,
  generators: duploGenerators,
  meta: duploMeta,
  flow: duploFlow,
  scripts: duploScripts,
};

export default duploFullDef;

export * from './_types';
