// File generated by 'npm run export'

import { CrossingsDefinition } from "./_types";

import crossingsAI from "./ai";
import crossingsAnim from "./anim";
import crossingsBoardBook from "./boards";
import crossingsSetupBook from "./setups";
import crossingsGraphics from "./graphics";
import crossingsInstruction from "./instructions";
import crossingsMeta from "./meta";
import crossingsPerformance from "./performance";
import crossingsFlow from "./flow";
import crossingsScripts from "./scripts";
import crossingsGenerators from "./generators";
import crossingsVariants from "./variants";

const crossingsDefinition: CrossingsDefinition = {
  AI: crossingsAI,
  anim: crossingsAnim,
  boards: crossingsBoardBook,
  setups: crossingsSetupBook,
  graphics: crossingsGraphics,
  instructions: crossingsInstruction,
  generators: crossingsGenerators,
  meta: crossingsMeta,
  performance: crossingsPerformance,
  flow: crossingsFlow,
  scripts: crossingsScripts,
  variants: crossingsVariants
};

export default crossingsDefinition;

export * from "./_types";
