// File generated by 'npm run export'

import { FullDef } from '../../../types';
import { GowiththefloeLayer, GowiththefloeMark, GowiththefloeCommand, GowiththefloeTurnPos, GowiththefloeTurnVar, GowiththefloeBattlePos, GowiththefloeBattleVar, GowiththefloeArtifactLayer, GowiththefloeGenerator, GowiththefloePhase, GowiththefloeTerrain, GowiththefloeUnit } from './_types';

import gowiththefloeAI from './ai';
import gowiththefloeBoard from './board';
import gowiththefloeSetup from './setup';
import gowiththefloeGraphics from './graphics';
import gowiththefloeInstruction from './instructions';
import gowiththefloeMeta from './meta';
import gowiththefloeFlow from './flow';
import gowiththefloeScripts from './scripts';
import gowiththefloeGenerators from './generators';

const gowiththefloeFullDef: FullDef<GowiththefloeLayer, GowiththefloeMark, GowiththefloeCommand, GowiththefloeTurnPos, GowiththefloeTurnVar, GowiththefloeBattlePos, GowiththefloeBattleVar, GowiththefloeArtifactLayer, GowiththefloeGenerator, GowiththefloePhase, GowiththefloeTerrain, GowiththefloeUnit> = {
  AI: gowiththefloeAI,
  board: gowiththefloeBoard,
  setup: gowiththefloeSetup,
  graphics: gowiththefloeGraphics,
  instructions: gowiththefloeInstruction,
  generators: gowiththefloeGenerators,
  meta: gowiththefloeMeta,
  flow: gowiththefloeFlow,
  scripts: gowiththefloeScripts,
};

export default gowiththefloeFullDef;

export * from './_types';
