// File generated by 'npm run export'

import { GowiththefloeDefinition } from "./_types";

import gowiththefloeAI from "./ai";
import gowiththefloeAnim from "./anim";
import gowiththefloeBoardBook from "./boards";
import gowiththefloeSetupBook from "./setups";
import gowiththefloeGraphics from "./graphics";
import gowiththefloeInstruction from "./instructions";
import gowiththefloeMeta from "./meta";
import gowiththefloePerformance from "./performance";
import gowiththefloeFlow from "./flow";
import gowiththefloeScripts from "./scripts";
import gowiththefloeGenerators from "./generators";
import gowiththefloeVariantsBook from "./variants";

const gowiththefloeDefinition: GowiththefloeDefinition = {
  AI: gowiththefloeAI,
  anim: gowiththefloeAnim,
  boards: gowiththefloeBoardBook,
  setups: gowiththefloeSetupBook,
  graphics: gowiththefloeGraphics,
  instructions: gowiththefloeInstruction,
  generators: gowiththefloeGenerators,
  meta: gowiththefloeMeta,
  performance: gowiththefloePerformance,
  flow: gowiththefloeFlow,
  scripts: gowiththefloeScripts,
  variants: gowiththefloeVariantsBook,
};

export default gowiththefloeDefinition;

export * from "./_types";
