// File generated by 'npm run export'

import { FullDef } from '../../../types';
import { GogolLayer, GogolMark, GogolCommand, GogolTurnPos, GogolTurnVar, GogolBattlePos, GogolBattleVar, GogolArtifactLayer, GogolGenerator, GogolPhase, GogolTerrain, GogolUnit } from './_types';

import gogolAI from './ai';
import gogolBoard from './board';
import gogolSetup from './setup';
import gogolGraphics from './graphics';
import gogolInstruction from './instructions';
import gogolMeta from './meta';
import gogolFlow from './flow';
import gogolScripts from './scripts';
import gogolGenerators from './generators';

const gogolFullDef: FullDef<GogolLayer, GogolMark, GogolCommand, GogolTurnPos, GogolTurnVar, GogolBattlePos, GogolBattleVar, GogolArtifactLayer, GogolGenerator, GogolPhase, GogolTerrain, GogolUnit> = {
  AI: gogolAI,
  board: gogolBoard,
  setup: gogolSetup,
  graphics: gogolGraphics,
  instructions: gogolInstruction,
  generators: gogolGenerators,
  meta: gogolMeta,
  flow: gogolFlow,
  scripts: gogolScripts,
};

export default gogolFullDef;

export * from './_types';
