// File generated by 'npm run export'

import { AtaxxDefinition } from "./_types";

import ataxxAI from "./ai";
import ataxxAnim from "./anim";
import ataxxBoardBook from "./boards";
import ataxxSetupBook from "./setups";
import ataxxGraphics from "./graphics";
import ataxxInstruction from "./instructions";
import ataxxMeta from "./meta";
import ataxxPerformance from "./performance";
import ataxxFlow from "./flow";
import ataxxScripts from "./scripts";
import ataxxGenerators from "./generators";
import ataxxVariants from "./variants";

const ataxxDefinition: AtaxxDefinition = {
  AI: ataxxAI,
  anim: ataxxAnim,
  boards: ataxxBoardBook,
  setups: ataxxSetupBook,
  graphics: ataxxGraphics,
  instructions: ataxxInstruction,
  generators: ataxxGenerators,
  meta: ataxxMeta,
  performance: ataxxPerformance,
  flow: ataxxFlow,
  scripts: ataxxScripts,
  variants: ataxxVariants
};

export default ataxxDefinition;

export * from "./_types";
