export default function templateIndex(gameId: string) {
  const capId = gameId[0].toUpperCase().concat(gameId.slice(1));
  return `// File generated by 'npm run export'

import { ${capId}Definition } from './_types';

import ${gameId}AI from './ai';
import ${gameId}Anim from './anim';
import ${gameId}BoardBook from './boards';
import ${gameId}SetupBook from './setup';
import ${gameId}Graphics from './graphics';
import ${gameId}Instruction from './instructions';
import ${gameId}Meta from './meta';
import ${gameId}Performance from './performance';
import ${gameId}Flow from './flow';
import ${gameId}Scripts from './scripts';
import ${gameId}Generators from './generators';

const ${gameId}Definition: ${capId}Definition = {
  AI: ${gameId}AI,
  anim: ${gameId}Anim,
  boards: ${gameId}BoardBook,
  setups: ${gameId}SetupBook,
  graphics: ${gameId}Graphics,
  instructions: ${gameId}Instruction,
  generators: ${gameId}Generators,
  meta: ${gameId}Meta,
  performance: ${gameId}Performance,
  flow: ${gameId}Flow,
  scripts: ${gameId}Scripts,
};

export default ${gameId}Definition;

export * from './_types';
`;
}
