// File generated by 'npm run export'

import { TyrannosDefinition } from "./_types";

import tyrannosAI from "./ai";
import tyrannosAnim from "./anim";
import tyrannosBoardBook from "./boards";
import tyrannosSetupBook from "./setups";
import tyrannosGraphics from "./graphics";
import tyrannosInstruction from "./instructions";
import tyrannosMeta from "./meta";
import tyrannosPerformance from "./performance";
import tyrannosFlow from "./flow";
import tyrannosScripts from "./scripts";
import tyrannosGenerators from "./generators";
import tyrannosVariants from "./variants";

const tyrannosDefinition: TyrannosDefinition = {
  AI: tyrannosAI,
  anim: tyrannosAnim,
  boards: tyrannosBoardBook,
  setups: tyrannosSetupBook,
  graphics: tyrannosGraphics,
  instructions: tyrannosInstruction,
  generators: tyrannosGenerators,
  meta: tyrannosMeta,
  performance: tyrannosPerformance,
  flow: tyrannosFlow,
  scripts: tyrannosScripts,
  variants: tyrannosVariants
};

export default tyrannosDefinition;

export * from "./_types";
