// File generated by 'npm run export'

import { SemaphorDefinition } from "./_types";

import semaphorAI from "./ai";
import semaphorAnim from "./anim";
import semaphorBoard from "./board";
import semaphorSetupBook from "./setups";
import semaphorGraphics from "./graphics";
import semaphorInstruction from "./instructions";
import semaphorMeta from "./meta";
import semaphorPerformance from "./performance";
import semaphorFlow from "./flow";
import semaphorScripts from "./scripts";
import semaphorGenerators from "./generators";

const semaphorDefinition: SemaphorDefinition = {
  AI: semaphorAI,
  anim: semaphorAnim,
  board: semaphorBoard,
  setups: semaphorSetupBook,
  graphics: semaphorGraphics,
  instructions: semaphorInstruction,
  generators: semaphorGenerators,
  meta: semaphorMeta,
  performance: semaphorPerformance,
  flow: semaphorFlow,
  scripts: semaphorScripts,
};

export default semaphorDefinition;

export * from "./_types";
