// File generated by 'npm run export'

import { SerauqsDefinition } from './_types';

import serauqsAI from './ai';
import serauqsBoard from './board';
import serauqsSetup from './setup';
import serauqsGraphics from './graphics';
import serauqsInstruction from './instructions';
import serauqsMeta from './meta';
import serauqsFlow from './flow';
import serauqsScripts from './scripts';
import serauqsGenerators from './generators';

const serauqsDefinition: SerauqsDefinition = {
  AI: serauqsAI,
  board: serauqsBoard,
  setup: serauqsSetup,
  graphics: serauqsGraphics,
  instructions: serauqsInstruction,
  generators: serauqsGenerators,
  meta: serauqsMeta,
  flow: serauqsFlow,
  scripts: serauqsScripts,
};

export default serauqsDefinition;

export * from './_types';
