// File generated by 'npm run export'

import { DaggersDefinition } from "./_types";

import daggersAI from "./ai";
import daggersAnim from "./anim";
import daggersBoardBook from "./boards";
import daggersSetupBook from "./setups";
import daggersGraphics from "./graphics";
import daggersInstruction from "./instructions";
import daggersMeta from "./meta";
import daggersPerformance from "./performance";
import daggersFlow from "./flow";
import daggersScripts from "./scripts";
import daggersGenerators from "./generators";
import daggersVariantsBook from "./variants";

const daggersDefinition: DaggersDefinition = {
  AI: daggersAI,
  anim: daggersAnim,
  boards: daggersBoardBook,
  setups: daggersSetupBook,
  graphics: daggersGraphics,
  instructions: daggersInstruction,
  generators: daggersGenerators,
  meta: daggersMeta,
  performance: daggersPerformance,
  flow: daggersFlow,
  scripts: daggersScripts,
  variants: daggersVariantsBook
};

export default daggersDefinition;

export * from "./_types";
