// File generated by 'npm run export'

import { DaggersDefinition } from './_types';

import daggersAI from './ai';
import daggersAnim from './anim';
import daggersBoard from './board';
import daggersSetup from './setup';
import daggersGraphics from './graphics';
import daggersInstruction from './instructions';
import daggersMeta from './meta';
import daggersPerformance from './performance';
import daggersFlow from './flow';
import daggersScripts from './scripts';
import daggersGenerators from './generators';

const daggersDefinition: DaggersDefinition = {
  AI: daggersAI,
  anim: daggersAnim,
  board: daggersBoard,
  setup: daggersSetup,
  graphics: daggersGraphics,
  instructions: daggersInstruction,
  generators: daggersGenerators,
  meta: daggersMeta,
  performance: daggersPerformance,
  flow: daggersFlow,
  scripts: daggersScripts,
};

export default daggersDefinition;

export * from './_types';
