// File generated by 'npm run export'

import { KachitknightDefinition } from "./_types";

import kachitknightAI from "./ai";
import kachitknightAnim from "./anim";
import kachitknightBoardBook from "./boards";
import kachitknightSetupBook from "./setups";
import kachitknightGraphics from "./graphics";
import kachitknightInstruction from "./instructions";
import kachitknightMeta from "./meta";
import kachitknightPerformance from "./performance";
import kachitknightFlow from "./flow";
import kachitknightScripts from "./scripts";
import kachitknightGenerators from "./generators";
import kachitknightVariants from "./variants";

const kachitknightDefinition: KachitknightDefinition = {
  AI: kachitknightAI,
  anim: kachitknightAnim,
  boards: kachitknightBoardBook,
  setups: kachitknightSetupBook,
  graphics: kachitknightGraphics,
  instructions: kachitknightInstruction,
  generators: kachitknightGenerators,
  meta: kachitknightMeta,
  performance: kachitknightPerformance,
  flow: kachitknightFlow,
  scripts: kachitknightScripts,
  variants: kachitknightVariants
};

export default kachitknightDefinition;

export * from "./_types";
