// File generated by 'npm run export'

import { FullDef } from '../../../types';
import { CoffeeLayer, CoffeeMark, CoffeeCommand, CoffeeTurnPos, CoffeeTurnVar, CoffeeBattlePos, CoffeeBattleVar, CoffeeArtifactLayer, CoffeeGenerator, CoffeePhase, CoffeeTerrain, CoffeeUnit } from './_types';

import coffeeAI from './ai';
import coffeeBoard from './board';
import coffeeSetup from './setup';
import coffeeGraphics from './graphics';
import coffeeInstruction from './instructions';
import coffeeMeta from './meta';
import coffeeFlow from './flow';
import coffeeScripts from './scripts';
import coffeeGenerators from './generators';

const coffeeFullDef: FullDef<CoffeeLayer, CoffeeMark, CoffeeCommand, CoffeeTurnPos, CoffeeTurnVar, CoffeeBattlePos, CoffeeBattleVar, CoffeeArtifactLayer, CoffeeGenerator, CoffeePhase, CoffeeTerrain, CoffeeUnit> = {
  AI: coffeeAI,
  board: coffeeBoard,
  setup: coffeeSetup,
  graphics: coffeeGraphics,
  instructions: coffeeInstruction,
  generators: coffeeGenerators,
  meta: coffeeMeta,
  flow: coffeeFlow,
  scripts: coffeeScripts,
};

export default coffeeFullDef;

export * from './_types';
