// File generated by 'npm run export'

import { CoffeeDefinition } from "./_types";

import coffeeAI from "./ai";
import coffeeAnim from "./anim";
import coffeeBoard from "./board";
import coffeeSetup from "./setup";
import coffeeGraphics from "./graphics";
import coffeeInstruction from "./instructions";
import coffeeMeta from "./meta";
import coffeePerformance from "./performance";
import coffeeFlow from "./flow";
import coffeeScripts from "./scripts";
import coffeeGenerators from "./generators";

const coffeeDefinition: CoffeeDefinition = {
  AI: coffeeAI,
  anim: coffeeAnim,
  board: coffeeBoard,
  setup: coffeeSetup,
  graphics: coffeeGraphics,
  instructions: coffeeInstruction,
  generators: coffeeGenerators,
  meta: coffeeMeta,
  performance: coffeePerformance,
  flow: coffeeFlow,
  scripts: coffeeScripts
};

export default coffeeDefinition;

export * from "./_types";
