// File generated by 'npm run export'

import { HippolytaDefinition } from "./_types";

import hippolytaAI from "./ai";
import hippolytaAnim from "./anim";
import hippolytaBoardBook from "./boards";
import hippolytaSetupBook from "./setups";
import hippolytaGraphics from "./graphics";
import hippolytaInstruction from "./instructions";
import hippolytaMeta from "./meta";
import hippolytaPerformance from "./performance";
import hippolytaFlow from "./flow";
import hippolytaScripts from "./scripts";
import hippolytaGenerators from "./generators";
import hippolytaVariants from "./variants";

const hippolytaDefinition: HippolytaDefinition = {
  AI: hippolytaAI,
  anim: hippolytaAnim,
  boards: hippolytaBoardBook,
  setups: hippolytaSetupBook,
  graphics: hippolytaGraphics,
  instructions: hippolytaInstruction,
  generators: hippolytaGenerators,
  meta: hippolytaMeta,
  performance: hippolytaPerformance,
  flow: hippolytaFlow,
  scripts: hippolytaScripts,
  variants: hippolytaVariants
};

export default hippolytaDefinition;

export * from "./_types";
