// File generated by 'npm run export'

import { DescentDefinition } from "./_types";

import descentAI from "./ai";
import descentAnim from "./anim";
import descentBoardBook from "./boards";
import descentSetupBook from "./setups";
import descentGraphics from "./graphics";
import descentInstruction from "./instructions";
import descentMeta from "./meta";
import descentPerformance from "./performance";
import descentFlow from "./flow";
import descentScripts from "./scripts";
import descentGenerators from "./generators";
import descentVariantsBook from "./variants";

const descentDefinition: DescentDefinition = {
  AI: descentAI,
  anim: descentAnim,
  boards: descentBoardBook,
  setups: descentSetupBook,
  graphics: descentGraphics,
  instructions: descentInstruction,
  generators: descentGenerators,
  meta: descentMeta,
  performance: descentPerformance,
  flow: descentFlow,
  scripts: descentScripts,
  variants: descentVariantsBook,
};

export default descentDefinition;

export * from "./_types";
