// File generated by 'npm run export'

import { DescentDefinition } from './_types';

import descentAI from './ai';
import descentBoard from './board';
import descentSetup from './setup';
import descentGraphics from './graphics';
import descentInstruction from './instructions';
import descentMeta from './meta';
import descentPerformance from './performance';
import descentFlow from './flow';
import descentScripts from './scripts';
import descentGenerators from './generators';

const descentDefinition: DescentDefinition = {
  AI: descentAI,
  board: descentBoard,
  setup: descentSetup,
  graphics: descentGraphics,
  instructions: descentInstruction,
  generators: descentGenerators,
  meta: descentMeta,
  performance: descentPerformance,
  flow: descentFlow,
  scripts: descentScripts,
};

export default descentDefinition;

export * from './_types';
