// File generated by 'npm run export'

import { FullDef } from '../../../types';
import { DescentArtifactLayer, DescentCommand, DescentGenerator, DescentLayer, DescentMark, DescentPhase, DescentTerrain, DescentUnit } from './_types';

import descentAI from './ai';
import descentBoard from './board';
import descentSetup from './setup';
import descentGraphics from './graphics';
import descentInstruction from './instructions';
import descentMeta from './meta';
import descentFlow from './flow';
import descentScripts from './scripts';
import descentGenerators from './generators';

const descentFullDef: FullDef<DescentArtifactLayer, DescentCommand, DescentGenerator, DescentLayer, DescentMark, DescentPhase, DescentTerrain, DescentUnit> = {
  AI: descentAI,
  board: descentBoard,
  setup: descentSetup,
  graphics: descentGraphics,
  instructions: descentInstruction,
  generators: descentGenerators,
  meta: descentMeta,
  flow: descentFlow,
  scripts: descentScripts,
};

export default descentFullDef;

export * from './_types';
