// File generated by 'npm run export'

import { HobbesDefinition } from "./_types";

import hobbesAI from "./ai";
import hobbesAnim from "./anim";
import hobbesBoardBook from "./boards";
import hobbesSetupBook from "./setups";
import hobbesGraphics from "./graphics";
import hobbesInstruction from "./instructions";
import hobbesMeta from "./meta";
import hobbesPerformance from "./performance";
import hobbesFlow from "./flow";
import hobbesScripts from "./scripts";
import hobbesGenerators from "./generators";
import hobbesVariants from "./variants";

const hobbesDefinition: HobbesDefinition = {
  AI: hobbesAI,
  anim: hobbesAnim,
  boards: hobbesBoardBook,
  setups: hobbesSetupBook,
  graphics: hobbesGraphics,
  instructions: hobbesInstruction,
  generators: hobbesGenerators,
  meta: hobbesMeta,
  performance: hobbesPerformance,
  flow: hobbesFlow,
  scripts: hobbesScripts,
  variants: hobbesVariants
};

export default hobbesDefinition;

export * from "./_types";
