import { AlgolIcon } from "../../../types/gamedef";

export type AlgolBoardEntityCode =
  | ["icon", AlgolIcon, 0 | 1 | 2, "none" | "mark" | "pot"]
  | ["mark"]
  | ["pot"]
  | ["row", 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10]
  | ["skip", 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9]
  | ["repeat", 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9];

export const codes: Record<string, AlgolBoardEntityCode> = {
  x: ["icon", "bishop", 0, "none"],
  N: ["icon", "bishop", 1, "none"],
  a: ["icon", "bishop", 2, "none"],
  t: ["icon", "bishop", 0, "mark"],
  g: ["icon", "bishop", 1, "mark"],
  A: ["icon", "bishop", 2, "mark"],
  D: ["icon", "bishop", 0, "pot"],
  d: ["icon", "bishop", 1, "pot"],
  l: ["icon", "bishop", 2, "pot"],
  X: ["icon", "rook", 0, "none"],
  B: ["icon", "rook", 1, "none"],
  s: ["icon", "rook", 2, "none"],
  e: ["icon", "rook", 0, "mark"],
  W: ["icon", "rook", 1, "mark"],
  4: ["icon", "rook", 2, "mark"],
  H: ["icon", "rook", 0, "pot"],
  G: ["icon", "rook", 1, "pot"],
  1: ["icon", "rook", 2, "pot"],
  c: ["icon", "pawn", 0, "none"],
  5: ["icon", "pawn", 1, "none"],
  U: ["icon", "pawn", 2, "none"],
  y: ["icon", "pawn", 0, "mark"],
  i: ["icon", "pawn", 1, "mark"],
  z: ["icon", "pawn", 2, "mark"],
  7: ["icon", "pawn", 0, "pot"],
  M: ["icon", "pawn", 1, "pot"],
  C: ["icon", "pawn", 2, "pot"],
  f: ["icon", "knight", 0, "none"],
  F: ["icon", "knight", 1, "none"],
  u: ["icon", "knight", 2, "none"],
  j: ["icon", "knight", 0, "mark"],
  b: ["icon", "knight", 1, "mark"],
  Z: ["icon", "knight", 2, "mark"],
  R: ["icon", "knight", 0, "pot"],
  w: ["icon", "knight", 1, "pot"],
  Q: ["icon", "knight", 2, "pot"],
  T: ["icon", "king", 0, "none"],
  V: ["icon", "king", 1, "none"],
  h: ["icon", "king", 2, "none"],
  8: ["icon", "king", 0, "mark"],
  J: ["icon", "king", 1, "mark"],
  S: ["icon", "king", 2, "mark"],
  3: ["icon", "king", 0, "pot"],
  6: ["icon", "king", 1, "pot"],
  0: ["icon", "king", 2, "pot"],
  2: ["icon", "queen", 0, "none"],
  r: ["icon", "queen", 1, "none"],
  q: ["icon", "queen", 2, "none"],
  Y: ["icon", "queen", 0, "mark"],
  O: ["icon", "queen", 1, "mark"],
  k: ["icon", "queen", 2, "mark"],
  n: ["icon", "queen", 0, "pot"],
  L: ["icon", "queen", 1, "pot"],
  K: ["icon", "queen", 2, "pot"],
  E: ["mark"],
  I: ["pot"],
  P: ["row", 2],
  m: ["row", 3],
  _: ["row", 4],
  "-": ["row", 5],
  ".": ["row", 6],
  ":": ["row", 7],
  9: ["row", 8],
  "!": ["row", 9],
  "=": ["row", 10],
  "?": ["skip", 1],
  o: ["skip", 2],
  p: ["skip", 3],
  v: ["skip", 4],
  "(": ["skip", 5],
  "+": ["skip", 6],
  "[": ["skip", 7],
  ";": ["skip", 8],
  "*": ["skip", 9],
  ")": ["repeat", 2],
  "]": ["repeat", 3],
  "<": ["repeat", 4],
  ">": ["repeat", 5],
  ",": ["repeat", 6],
  "&": ["repeat", 7],
  "'": ["repeat", 8],
  "}": ["repeat", 9],
};
