// File generated by 'npm run export'

import { SquavaDefinition } from "./_types";

import squavaAI from "./ai";
import squavaAnim from "./anim";
import squavaBoardBook from "./boards";
import squavaSetupBook from "./setups";
import squavaGraphics from "./graphics";
import squavaInstruction from "./instructions";
import squavaMeta from "./meta";
import squavaPerformance from "./performance";
import squavaFlow from "./flow";
import squavaScripts from "./scripts";
import squavaGenerators from "./generators";
import squavaVariants from "./variants";

const squavaDefinition: SquavaDefinition = {
  AI: squavaAI,
  anim: squavaAnim,
  boards: squavaBoardBook,
  setups: squavaSetupBook,
  graphics: squavaGraphics,
  instructions: squavaInstruction,
  generators: squavaGenerators,
  meta: squavaMeta,
  performance: squavaPerformance,
  flow: squavaFlow,
  scripts: squavaScripts,
  variants: squavaVariants
};

export default squavaDefinition;

export * from "./_types";
