// File generated by 'npm run export'

import { KickrunDefinition } from "./_types";

import kickrunAI from "./ai";
import kickrunAnim from "./anim";
import kickrunBoard from "./board";
import kickrunSetupBook from "./setups";
import kickrunGraphics from "./graphics";
import kickrunInstruction from "./instructions";
import kickrunMeta from "./meta";
import kickrunPerformance from "./performance";
import kickrunFlow from "./flow";
import kickrunScripts from "./scripts";
import kickrunGenerators from "./generators";

const kickrunDefinition: KickrunDefinition = {
  AI: kickrunAI,
  anim: kickrunAnim,
  board: kickrunBoard,
  setups: kickrunSetupBook,
  graphics: kickrunGraphics,
  instructions: kickrunInstruction,
  generators: kickrunGenerators,
  meta: kickrunMeta,
  performance: kickrunPerformance,
  flow: kickrunFlow,
  scripts: kickrunScripts,
};

export default kickrunDefinition;

export * from "./_types";
