import prettier from "prettier";
import fs from "fs-extra";
import path from "path";
import { AlgolListing } from "../../../types";

const outFolder = path.join(__dirname, "../../dist/listings/news");

export const makeNewsListing = (newsId: string) => {
  const yaml = require(`../../../content/dist/news/${newsId}/listing`).listing;
  const listing: AlgolListing = {
    blurb: yaml.blurb,
    preloads: yaml.preloads,
    url: `/news/${yaml.slug}`,
    title: yaml.title,
    sort: yaml.sort,
    thumbdata: yaml.thumbdata,
  };
  const code = `// generated by makeNewsListing
import { AlgolListing } from '../../../../types'

export const ${newsId}: AlgolListing = ${JSON.stringify(listing)};

export default ${newsId}
`;
  fs.ensureDirSync(outFolder);
  fs.writeFileSync(
    path.join(outFolder, `${newsId}.ts`),
    prettier.format(code, { filepath: "foo.ts" })
  );
  console.log("Made listing for news item", newsId);
};
