import prettier from "prettier";
import fs from "fs-extra";
import path from "path";
import { GameId } from "../../../games/dist/list";
import meta from "../../../games/dist/meta";
import actionShots from "../../../graphics/dist/allRegularActionShots";
import { AlgolArticleListing } from "../../../types";
import { gameSlug } from "../../../common/utils";

const outFolder = path.join(__dirname, "../../dist/listings/games");

export const makeGameListing = (gameId: GameId) => {
  const listing: AlgolArticleListing = {
    blurb: meta[gameId].tagline,
    preloads: [],
    url: `/games/${gameSlug(meta[gameId])}`,
    title: meta[gameId].name,
    sort: gameId,
    thumbdata: actionShots[gameId],
  };
  const code = `// generated by makeGameListing
import { AlgolArticleListing } from '../../../../types'

export const ${gameId}: AlgolArticleListing = ${JSON.stringify(listing)};

export default ${gameId}
`;
  fs.ensureDirSync(outFolder);
  fs.writeFileSync(
    path.join(outFolder, `${gameId}.ts`),
    prettier.format(code, { filepath: "foo.ts" })
  );
  console.log("Made listing for game", gameId);
};
