import prettier from "prettier";
import fs from "fs-extra";
import path from "path";
import { AlgolArticleListing } from "../../../types";

const outFolder = path.join(__dirname, "../../dist/listings/tags");

export const makeTagListing = (tagId: string) => {
  const meta = require(`../../../content/dist/tags/${tagId}/listing`).listing;
  const listing: AlgolArticleListing = {
    blurb: meta.blurb,
    preloads: meta.preloads,
    url: `/tags/${meta.slug}`,
    title: meta.title,
    sort: meta.sort,
    thumbdata: meta.thumbdata,
  };
  const code = `// generated by makeTagListing
import { AlgolArticleListing } from '../../../../types'

export const ${tagId}: AlgolArticleListing = ${JSON.stringify(listing)};

export default ${tagId}
`;
  fs.ensureDirSync(outFolder);
  fs.writeFileSync(
    path.join(outFolder, `${tagId}.ts`),
    prettier.format(code, { filepath: "foo.ts" })
  );
  console.log("Made listing for tag", tagId);
};
