// File generated by 'npm run export'

import { ScatterDefinition } from "./_types";

import scatterAI from "./ai";
import scatterAnim from "./anim";
import scatterBoardBook from "./boards";
import scatterSetupBook from "./setups";
import scatterGraphics from "./graphics";
import scatterInstruction from "./instructions";
import scatterMeta from "./meta";
import scatterPerformance from "./performance";
import scatterFlow from "./flow";
import scatterScripts from "./scripts";
import scatterGenerators from "./generators";
import scatterVariants from "./variants";

const scatterDefinition: ScatterDefinition = {
  AI: scatterAI,
  anim: scatterAnim,
  boards: scatterBoardBook,
  setups: scatterSetupBook,
  graphics: scatterGraphics,
  instructions: scatterInstruction,
  generators: scatterGenerators,
  meta: scatterMeta,
  performance: scatterPerformance,
  flow: scatterFlow,
  scripts: scatterScripts,
  variants: scatterVariants
};

export default scatterDefinition;

export * from "./_types";
