// File generated by 'npm run export'

import { StoogesDefinition } from "./_types";

import stoogesAI from "./ai";
import stoogesAnim from "./anim";
import stoogesBoardBook from "./boards";
import stoogesSetupBook from "./setups";
import stoogesGraphics from "./graphics";
import stoogesInstruction from "./instructions";
import stoogesMeta from "./meta";
import stoogesPerformance from "./performance";
import stoogesFlow from "./flow";
import stoogesScripts from "./scripts";
import stoogesGenerators from "./generators";
import stoogesVariants from "./variants";

const stoogesDefinition: StoogesDefinition = {
  AI: stoogesAI,
  anim: stoogesAnim,
  boards: stoogesBoardBook,
  setups: stoogesSetupBook,
  graphics: stoogesGraphics,
  instructions: stoogesInstruction,
  generators: stoogesGenerators,
  meta: stoogesMeta,
  performance: stoogesPerformance,
  flow: stoogesFlow,
  scripts: stoogesScripts,
  variants: stoogesVariants
};

export default stoogesDefinition;

export * from "./_types";
