// File generated by 'npm run export'

import { PaperneutronDefinition } from "./_types";

import paperneutronAI from "./ai";
import paperneutronAnim from "./anim";
import paperneutronBoardBook from "./boards";
import paperneutronSetupBook from "./setups";
import paperneutronGraphics from "./graphics";
import paperneutronInstruction from "./instructions";
import paperneutronMeta from "./meta";
import paperneutronPerformance from "./performance";
import paperneutronFlow from "./flow";
import paperneutronScripts from "./scripts";
import paperneutronGenerators from "./generators";
import paperneutronVariants from "./variants";

const paperneutronDefinition: PaperneutronDefinition = {
  AI: paperneutronAI,
  anim: paperneutronAnim,
  boards: paperneutronBoardBook,
  setups: paperneutronSetupBook,
  graphics: paperneutronGraphics,
  instructions: paperneutronInstruction,
  generators: paperneutronGenerators,
  meta: paperneutronMeta,
  performance: paperneutronPerformance,
  flow: paperneutronFlow,
  scripts: paperneutronScripts,
  variants: paperneutronVariants
};

export default paperneutronDefinition;

export * from "./_types";
