// File generated by 'npm run export'

import { YonmoqueDefinition } from "./_types";

import yonmoqueAI from "./ai";
import yonmoqueAnim from "./anim";
import yonmoqueBoardBook from "./boards";
import yonmoqueSetupBook from "./setups";
import yonmoqueGraphics from "./graphics";
import yonmoqueInstruction from "./instructions";
import yonmoqueMeta from "./meta";
import yonmoquePerformance from "./performance";
import yonmoqueFlow from "./flow";
import yonmoqueScripts from "./scripts";
import yonmoqueGenerators from "./generators";
import yonmoqueVariants from "./variants";

const yonmoqueDefinition: YonmoqueDefinition = {
  AI: yonmoqueAI,
  anim: yonmoqueAnim,
  boards: yonmoqueBoardBook,
  setups: yonmoqueSetupBook,
  graphics: yonmoqueGraphics,
  instructions: yonmoqueInstruction,
  generators: yonmoqueGenerators,
  meta: yonmoqueMeta,
  performance: yonmoquePerformance,
  flow: yonmoqueFlow,
  scripts: yonmoqueScripts,
  variants: yonmoqueVariants
};

export default yonmoqueDefinition;

export * from "./_types";
