// File generated by 'npm run export'

import { ZoneshDefinition } from "./_types";

import zoneshAI from "./ai";
import zoneshAnim from "./anim";
import zoneshBoardBook from "./boards";
import zoneshSetupBook from "./setups";
import zoneshGraphics from "./graphics";
import zoneshInstruction from "./instructions";
import zoneshMeta from "./meta";
import zoneshPerformance from "./performance";
import zoneshFlow from "./flow";
import zoneshScripts from "./scripts";
import zoneshGenerators from "./generators";
import zoneshVariants from "./variants";

const zoneshDefinition: ZoneshDefinition = {
  AI: zoneshAI,
  anim: zoneshAnim,
  boards: zoneshBoardBook,
  setups: zoneshSetupBook,
  graphics: zoneshGraphics,
  instructions: zoneshInstruction,
  generators: zoneshGenerators,
  meta: zoneshMeta,
  performance: zoneshPerformance,
  flow: zoneshFlow,
  scripts: zoneshScripts,
  variants: zoneshVariants
};

export default zoneshDefinition;

export * from "./_types";
