// File generated by 'npm run export'

import { FullDef } from '../../../types';
import { OrthokonLayer, OrthokonMark, OrthokonCommand, OrthokonTurnPos, OrthokonTurnVar, OrthokonBattlePos, OrthokonBattleVar, OrthokonArtifactLayer, OrthokonGenerator, OrthokonPhase, OrthokonTerrain, OrthokonUnit } from './_types';

import orthokonAI from './ai';
import orthokonBoard from './board';
import orthokonSetup from './setup';
import orthokonGraphics from './graphics';
import orthokonInstruction from './instructions';
import orthokonMeta from './meta';
import orthokonFlow from './flow';
import orthokonScripts from './scripts';
import orthokonGenerators from './generators';

const orthokonFullDef: FullDef<OrthokonLayer, OrthokonMark, OrthokonCommand, OrthokonTurnPos, OrthokonTurnVar, OrthokonBattlePos, OrthokonBattleVar, OrthokonArtifactLayer, OrthokonGenerator, OrthokonPhase, OrthokonTerrain, OrthokonUnit> = {
  AI: orthokonAI,
  board: orthokonBoard,
  setup: orthokonSetup,
  graphics: orthokonGraphics,
  instructions: orthokonInstruction,
  generators: orthokonGenerators,
  meta: orthokonMeta,
  flow: orthokonFlow,
  scripts: orthokonScripts,
};

export default orthokonFullDef;

export * from './_types';
