// File generated by 'npm run export'

import { OrthokonDefinition } from "./_types";

import orthokonAI from "./ai";
import orthokonAnim from "./anim";
import orthokonBoardBook from "./boards";
import orthokonSetupBook from "./setups";
import orthokonGraphics from "./graphics";
import orthokonInstruction from "./instructions";
import orthokonMeta from "./meta";
import orthokonPerformance from "./performance";
import orthokonFlow from "./flow";
import orthokonScripts from "./scripts";
import orthokonGenerators from "./generators";
import orthokonVariantsBook from "./variants";

const orthokonDefinition: OrthokonDefinition = {
  AI: orthokonAI,
  anim: orthokonAnim,
  boards: orthokonBoardBook,
  setups: orthokonSetupBook,
  graphics: orthokonGraphics,
  instructions: orthokonInstruction,
  generators: orthokonGenerators,
  meta: orthokonMeta,
  performance: orthokonPerformance,
  flow: orthokonFlow,
  scripts: orthokonScripts,
  variants: orthokonVariantsBook
};

export default orthokonDefinition;

export * from "./_types";
