// File generated by 'npm run export'

import { UglyduckDefinition } from './_types';

import uglyduckAI from './ai';
import uglyduckBoard from './board';
import uglyduckSetup from './setup';
import uglyduckGraphics from './graphics';
import uglyduckInstruction from './instructions';
import uglyduckMeta from './meta';
import uglyduckFlow from './flow';
import uglyduckScripts from './scripts';
import uglyduckGenerators from './generators';

const uglyduckDefinition: UglyduckDefinition = {
  AI: uglyduckAI,
  board: uglyduckBoard,
  setup: uglyduckSetup,
  graphics: uglyduckGraphics,
  instructions: uglyduckInstruction,
  generators: uglyduckGenerators,
  meta: uglyduckMeta,
  flow: uglyduckFlow,
  scripts: uglyduckScripts,
};

export default uglyduckDefinition;

export * from './_types';
