// File generated by 'npm run export'

import { FullDef } from '../../types';
import { SerauqsArtifactLayer, SerauqsCommand, SerauqsGenerator, SerauqsLayer, SerauqsMark, SerauqsPhase, SerauqsTerrain, SerauqsUnit } from './_types';

import serauqsAI from './ai';
import serauqsBoard from './board';
import serauqsSetup from './setup';
import serauqsGraphics from './graphics';
import serauqsInstruction from './instructions';
import serauqsMeta from './meta';
import serauqsFlow from './flow';
import serauqsScripts from './scripts';
import serauqsGenerators from './generators';

const serauqsFullDef: FullDef<SerauqsArtifactLayer, SerauqsCommand, SerauqsGenerator, SerauqsLayer, SerauqsMark, SerauqsPhase, SerauqsTerrain, SerauqsUnit> = {
  AI: serauqsAI,
  board: serauqsBoard,
  setup: serauqsSetup,
  graphics: serauqsGraphics,
  instructions: serauqsInstruction,
  generators: serauqsGenerators,
  meta: serauqsMeta,
  flow: serauqsFlow,
  scripts: serauqsScripts,
};

export default serauqsFullDef;

export * from './_types';
