// File generated by 'npm run export'

import { IagoDefinition } from "./_types";

import iagoAI from "./ai";
import iagoAnim from "./anim";
import iagoBoardBook from "./boards";
import iagoSetupBook from "./setups";
import iagoGraphics from "./graphics";
import iagoInstruction from "./instructions";
import iagoMeta from "./meta";
import iagoPerformance from "./performance";
import iagoFlow from "./flow";
import iagoScripts from "./scripts";
import iagoGenerators from "./generators";
import iagoVariants from "./variants";

const iagoDefinition: IagoDefinition = {
  AI: iagoAI,
  anim: iagoAnim,
  boards: iagoBoardBook,
  setups: iagoSetupBook,
  graphics: iagoGraphics,
  instructions: iagoInstruction,
  generators: iagoGenerators,
  meta: iagoMeta,
  performance: iagoPerformance,
  flow: iagoFlow,
  scripts: iagoScripts,
  variants: iagoVariants
};

export default iagoDefinition;

export * from "./_types";
