import fs from "fs-extra";
import path from "path";
import { newsList } from "../../content/dist/newsList";

const out = path.join(__dirname, "../pages/news");
fs.emptyDirSync(out);

for (const data of newsList) {
  const content = `
// Generated by the makeNewsPages command

import React, { Fragment } from "react";

import Head from "next/head";
import { ArticlePage } from "../../../../ui/src/components/ArticlePage";
import { pageActions } from "../../../helpers";
import { news } from "../../../../content/dist/news/${data.id}/news";
import { listing } from "../../../../content/dist/news/${data.id}/listing";

export const Article = () => {
  return (
    <Fragment>
      <Head>
        <meta property="og:site_name" content="Chessicals"/>
        <meta property="og:image" content={listing.mainImage} />
        <meta property="og:title" content={listing.title} />
        <meta property="og:description" content={listing.blurb} />
        <title>{listing.title}</title>
      </Head>
      <ArticlePage
        category="News"
        data={listing}
        actions={pageActions}
        html={news}
      />
    </Fragment>
  );
};

export default Article;
`;
  fs.emptyDirSync(path.join(out, data.slug));
  fs.writeFileSync(path.join(out, data.slug, "index.tsx"), content);
  console.log("Created page for news item", data.id, data.slug);
}
