import fs from "fs-extra";
import path from "path";
import prettier from "prettier";
import { newsList } from "../../content/dist/newsList";

const out = path.join(__dirname, "../pages/news");
fs.ensureDirSync(out);

for (const data of newsList) {
  const content = `
// Generated by the makeNewsPages command

import React, { Fragment, useEffect } from "react";

import Head from "next/head";
import { ArticlePage } from "../../../../ui/src/components/ArticlePage";
import { pageActions } from "../../../helpers";
import { news } from "../../../../content/dist/news/${data.id}/news";

export const Article = () => {
  const title = \`${data.id} - ${data.title}\`;
  ${
    data.games.length
      ? `useEffect(() => {
    ${data.games
      .map(gameId => `pageActions.prefetch('/games/${gameId}')`)
      .join("; ")}
  }, [])`
      : ""
  }
  return (
    <Fragment>
      <Head>
        <meta property="og:site_name" content="Chessicals"/>
        <meta property="og:image" content="${data.mainImage}" />
        <meta property="og:title" content={title} />
        <meta property="og:description" content="${data.blurb}"/>
        <title>{title}</title>
      </Head>
      <ArticlePage
        title={title}
        actions={pageActions}
        html={news}
      />
    </Fragment>
  );
};

export default Article;
`;
  fs.emptyDirSync(path.join(out, data.slug));
  fs.writeFileSync(
    path.join(out, data.slug, "index.tsx"),
    prettier.format(content, { filepath: "foo.ts" })
  );
  console.log("Created page for news item", data.id, data.slug);
}
