// File generated by 'npm run export'

import { MurusgallicusadvancedDefinition } from './_types';

import murusgallicusadvancedAI from './ai';
import murusgallicusadvancedBoard from './board';
import murusgallicusadvancedSetup from './setup';
import murusgallicusadvancedGraphics from './graphics';
import murusgallicusadvancedInstruction from './instructions';
import murusgallicusadvancedMeta from './meta';
import murusgallicusadvancedFlow from './flow';
import murusgallicusadvancedScripts from './scripts';
import murusgallicusadvancedGenerators from './generators';

const murusgallicusadvancedDefinition: MurusgallicusadvancedDefinition = {
  AI: murusgallicusadvancedAI,
  board: murusgallicusadvancedBoard,
  setup: murusgallicusadvancedSetup,
  graphics: murusgallicusadvancedGraphics,
  instructions: murusgallicusadvancedInstruction,
  generators: murusgallicusadvancedGenerators,
  meta: murusgallicusadvancedMeta,
  flow: murusgallicusadvancedFlow,
  scripts: murusgallicusadvancedScripts,
};

export default murusgallicusadvancedDefinition;

export * from './_types';
