// File generated by 'npm run export'

import { ConnectfourDefinition } from "./_types";

import connectfourAI from "./ai";
import connectfourAnim from "./anim";
import connectfourBoardBook from "./boards";
import connectfourSetupBook from "./setups";
import connectfourGraphics from "./graphics";
import connectfourInstruction from "./instructions";
import connectfourMeta from "./meta";
import connectfourPerformance from "./performance";
import connectfourFlow from "./flow";
import connectfourScripts from "./scripts";
import connectfourGenerators from "./generators";
import connectfourVariants from "./variants";

const connectfourDefinition: ConnectfourDefinition = {
  AI: connectfourAI,
  anim: connectfourAnim,
  boards: connectfourBoardBook,
  setups: connectfourSetupBook,
  graphics: connectfourGraphics,
  instructions: connectfourInstruction,
  generators: connectfourGenerators,
  meta: connectfourMeta,
  performance: connectfourPerformance,
  flow: connectfourFlow,
  scripts: connectfourScripts,
  variants: connectfourVariants
};

export default connectfourDefinition;

export * from "./_types";
