// File generated by 'npm run export'

import { FullDef } from '../../../types';
import { KriegArtifactLayer, KriegCommand, KriegGenerator, KriegLayer, KriegMark, KriegPhase, KriegTerrain, KriegUnit } from './_types';

import kriegAI from './ai';
import kriegBoard from './board';
import kriegSetup from './setup';
import kriegGraphics from './graphics';
import kriegInstruction from './instructions';
import kriegMeta from './meta';
import kriegFlow from './flow';
import kriegScripts from './scripts';
import kriegGenerators from './generators';

const kriegFullDef: FullDef<KriegArtifactLayer, KriegCommand, KriegGenerator, KriegLayer, KriegMark, KriegPhase, KriegTerrain, KriegUnit> = {
  AI: kriegAI,
  board: kriegBoard,
  setup: kriegSetup,
  graphics: kriegGraphics,
  instructions: kriegInstruction,
  generators: kriegGenerators,
  meta: kriegMeta,
  flow: kriegFlow,
  scripts: kriegScripts,
};

export default kriegFullDef;

export * from './_types';
