// File generated by 'npm run export'

import { TobitoDefinition } from "./_types";

import tobitoAI from "./ai";
import tobitoAnim from "./anim";
import tobitoBoardBook from "./boards";
import tobitoSetupBook from "./setups";
import tobitoGraphics from "./graphics";
import tobitoInstruction from "./instructions";
import tobitoMeta from "./meta";
import tobitoPerformance from "./performance";
import tobitoFlow from "./flow";
import tobitoScripts from "./scripts";
import tobitoGenerators from "./generators";
import tobitoVariants from "./variants";

const tobitoDefinition: TobitoDefinition = {
  AI: tobitoAI,
  anim: tobitoAnim,
  boards: tobitoBoardBook,
  setups: tobitoSetupBook,
  graphics: tobitoGraphics,
  instructions: tobitoInstruction,
  generators: tobitoGenerators,
  meta: tobitoMeta,
  performance: tobitoPerformance,
  flow: tobitoFlow,
  scripts: tobitoScripts,
  variants: tobitoVariants
};

export default tobitoDefinition;

export * from "./_types";
