// File generated by 'npm run export'

import { AriesDefinition } from './_types';

import ariesAI from './ai';
import ariesBoard from './board';
import ariesSetup from './setup';
import ariesGraphics from './graphics';
import ariesInstruction from './instructions';
import ariesMeta from './meta';
import ariesFlow from './flow';
import ariesScripts from './scripts';
import ariesGenerators from './generators';

const ariesDefinition: AriesDefinition = {
  AI: ariesAI,
  board: ariesBoard,
  setup: ariesSetup,
  graphics: ariesGraphics,
  instructions: ariesInstruction,
  generators: ariesGenerators,
  meta: ariesMeta,
  flow: ariesFlow,
  scripts: ariesScripts,
};

export default ariesDefinition;

export * from './_types';
