// File generated by 'npm run export'

import { BreakthroughDefinition } from "./_types";

import breakthroughAI from "./ai";
import breakthroughAnim from "./anim";
import breakthroughBoardBook from "./boards";
import breakthroughSetupBook from "./setups";
import breakthroughGraphics from "./graphics";
import breakthroughInstruction from "./instructions";
import breakthroughMeta from "./meta";
import breakthroughPerformance from "./performance";
import breakthroughFlow from "./flow";
import breakthroughScripts from "./scripts";
import breakthroughGenerators from "./generators";
import breakthroughVariants from "./variants";

const breakthroughDefinition: BreakthroughDefinition = {
  AI: breakthroughAI,
  anim: breakthroughAnim,
  boards: breakthroughBoardBook,
  setups: breakthroughSetupBook,
  graphics: breakthroughGraphics,
  instructions: breakthroughInstruction,
  generators: breakthroughGenerators,
  meta: breakthroughMeta,
  performance: breakthroughPerformance,
  flow: breakthroughFlow,
  scripts: breakthroughScripts,
  variants: breakthroughVariants
};

export default breakthroughDefinition;

export * from "./_types";
