// File generated by 'npm run export'

import { OrthokonDefinition } from './_types';

import orthokonAI from './ai';
import orthokonBoard from './board';
import orthokonSetup from './setup';
import orthokonGraphics from './graphics';
import orthokonInstruction from './instructions';
import orthokonMeta from './meta';
import orthokonFlow from './flow';
import orthokonScripts from './scripts';
import orthokonGenerators from './generators';

const orthokonDefinition: OrthokonDefinition = {
  AI: orthokonAI,
  board: orthokonBoard,
  setup: orthokonSetup,
  graphics: orthokonGraphics,
  instructions: orthokonInstruction,
  generators: orthokonGenerators,
  meta: orthokonMeta,
  flow: orthokonFlow,
  scripts: orthokonScripts,
};

export default orthokonDefinition;

export * from './_types';
