// File generated by 'npm run export'

import { MadbishopsDefinition } from "./_types";

import madbishopsAI from "./ai";
import madbishopsAnim from "./anim";
import madbishopsBoardBook from "./boards";
import madbishopsSetupBook from "./setups";
import madbishopsGraphics from "./graphics";
import madbishopsInstruction from "./instructions";
import madbishopsMeta from "./meta";
import madbishopsPerformance from "./performance";
import madbishopsFlow from "./flow";
import madbishopsScripts from "./scripts";
import madbishopsGenerators from "./generators";
import madbishopsVariants from "./variants";

const madbishopsDefinition: MadbishopsDefinition = {
  AI: madbishopsAI,
  anim: madbishopsAnim,
  boards: madbishopsBoardBook,
  setups: madbishopsSetupBook,
  graphics: madbishopsGraphics,
  instructions: madbishopsInstruction,
  generators: madbishopsGenerators,
  meta: madbishopsMeta,
  performance: madbishopsPerformance,
  flow: madbishopsFlow,
  scripts: madbishopsScripts,
  variants: madbishopsVariants
};

export default madbishopsDefinition;

export * from "./_types";
