import { MadbishopsDefinition } from "./_types";

const madbishopsSetupBook: MadbishopsDefinition["setups"] = {
  basic: {
    bishops: {
      1: [
        "a1",
        "a5",
        "a9",
        "b2",
        "b6",
        "c3",
        "c7",
        "c9",
        "d4",
        "d10",
        "e1",
        "e5",
        "e7",
        "f2",
        "f8",
        "g3",
        "g5",
        "g9",
        "h6",
        "h10",
        "i1",
        "i3",
        "i7",
        "j4",
        "j8",
      ],
      2: [
        "a3",
        "a7",
        "b4",
        "b8",
        "b10",
        "c1",
        "c5",
        "d2",
        "d6",
        "d8",
        "e3",
        "e9",
        "f4",
        "f6",
        "f10",
        "g1",
        "g7",
        "h2",
        "h4",
        "h8",
        "i5",
        "i9",
        "j2",
        "j6",
        "j10",
      ],
    },
  },
};

export default madbishopsSetupBook;
