// File generated by 'npm run export'

import { TowertwoDefinition } from "./_types";

import towertwoAI from "./ai";
import towertwoAnim from "./anim";
import towertwoBoardBook from "./boards";
import towertwoSetupBook from "./setups";
import towertwoGraphics from "./graphics";
import towertwoInstruction from "./instructions";
import towertwoMeta from "./meta";
import towertwoPerformance from "./performance";
import towertwoFlow from "./flow";
import towertwoScripts from "./scripts";
import towertwoGenerators from "./generators";
import towertwoVariants from "./variants";

const towertwoDefinition: TowertwoDefinition = {
  AI: towertwoAI,
  anim: towertwoAnim,
  boards: towertwoBoardBook,
  setups: towertwoSetupBook,
  graphics: towertwoGraphics,
  instructions: towertwoInstruction,
  generators: towertwoGenerators,
  meta: towertwoMeta,
  performance: towertwoPerformance,
  flow: towertwoFlow,
  scripts: towertwoScripts,
  variants: towertwoVariants
};

export default towertwoDefinition;

export * from "./_types";
