// File generated by 'npm run export'

import { CampaignDefinition } from "./_types";

import campaignAI from "./ai";
import campaignAnim from "./anim";
import campaignBoardBook from "./boards";
import campaignSetupBook from "./setups";
import campaignGraphics from "./graphics";
import campaignInstruction from "./instructions";
import campaignMeta from "./meta";
import campaignPerformance from "./performance";
import campaignFlow from "./flow";
import campaignScripts from "./scripts";
import campaignGenerators from "./generators";
import campaignVariants from "./variants";

const campaignDefinition: CampaignDefinition = {
  AI: campaignAI,
  anim: campaignAnim,
  boards: campaignBoardBook,
  setups: campaignSetupBook,
  graphics: campaignGraphics,
  instructions: campaignInstruction,
  generators: campaignGenerators,
  meta: campaignMeta,
  performance: campaignPerformance,
  flow: campaignFlow,
  scripts: campaignScripts,
  variants: campaignVariants
};

export default campaignDefinition;

export * from "./_types";
