// File generated by 'npm run export'

import { DesdemonaDefinition } from "./_types";

import desdemonaAI from "./ai";
import desdemonaAnim from "./anim";
import desdemonaBoardBook from "./boards";
import desdemonaSetupBook from "./setups";
import desdemonaGraphics from "./graphics";
import desdemonaInstruction from "./instructions";
import desdemonaMeta from "./meta";
import desdemonaPerformance from "./performance";
import desdemonaFlow from "./flow";
import desdemonaScripts from "./scripts";
import desdemonaGenerators from "./generators";
import desdemonaVariants from "./variants";

const desdemonaDefinition: DesdemonaDefinition = {
  AI: desdemonaAI,
  anim: desdemonaAnim,
  boards: desdemonaBoardBook,
  setups: desdemonaSetupBook,
  graphics: desdemonaGraphics,
  instructions: desdemonaInstruction,
  generators: desdemonaGenerators,
  meta: desdemonaMeta,
  performance: desdemonaPerformance,
  flow: desdemonaFlow,
  scripts: desdemonaScripts,
  variants: desdemonaVariants
};

export default desdemonaDefinition;

export * from "./_types";
