// File generated by 'npm run export'

import { FullDef } from '../../types';
import { TransetArtifactLayer, TransetCommand, TransetGenerator, TransetLayer, TransetMark, TransetPhase, TransetTerrain, TransetUnit } from './_types';

import transetAI from './ai';
import transetBoard from './board';
import transetSetup from './setup';
import transetGraphics from './graphics';
import transetInstruction from './instructions';
import transetMeta from './meta';
import transetFlow from './flow';
import transetScripts from './scripts';
import transetGenerators from './generators';

const transetFullDef: FullDef<TransetArtifactLayer, TransetCommand, TransetGenerator, TransetLayer, TransetMark, TransetPhase, TransetTerrain, TransetUnit> = {
  AI: transetAI,
  board: transetBoard,
  setup: transetSetup,
  graphics: transetGraphics,
  instructions: transetInstruction,
  generators: transetGenerators,
  meta: transetMeta,
  flow: transetFlow,
  scripts: transetScripts,
};

export default transetFullDef;

export * from './_types';
