import { typeSignature } from "../../../../types";

export default function templateIndex(gameId) {
  const fsig = typeSignature("FullDef", gameId);
  return `// File generated by 'npm run export'

import { FullDef } from '../../../types';
import { ${fsig} } from './_types';

import ${gameId}AI from './ai';
import ${gameId}Board from './board';
import ${gameId}Setup from './setup';
import ${gameId}Graphics from './graphics';
import ${gameId}Instruction from './instructions';
import ${gameId}Meta from './meta';
import ${gameId}Flow from './flow';
import ${gameId}Scripts from './scripts';
import ${gameId}Generators from './generators';

const ${gameId}FullDef: FullDef<${fsig}> = {
  AI: ${gameId}AI,
  board: ${gameId}Board,
  setup: ${gameId}Setup,
  graphics: ${gameId}Graphics,
  instructions: ${gameId}Instruction,
  generators: ${gameId}Generators,
  meta: ${gameId}Meta,
  flow: ${gameId}Flow,
  scripts: ${gameId}Scripts,
};

export default ${gameId}FullDef;

export * from './_types';
`;
}
