// File generated by 'npm run export'

import { MomentumDefinition } from "./_types";

import momentumAI from "./ai";
import momentumAnim from "./anim";
import momentumBoard from "./board";
import momentumSetupBook from "./setups";
import momentumGraphics from "./graphics";
import momentumInstruction from "./instructions";
import momentumMeta from "./meta";
import momentumPerformance from "./performance";
import momentumFlow from "./flow";
import momentumScripts from "./scripts";
import momentumGenerators from "./generators";

const momentumDefinition: MomentumDefinition = {
  AI: momentumAI,
  anim: momentumAnim,
  board: momentumBoard,
  setups: momentumSetupBook,
  graphics: momentumGraphics,
  instructions: momentumInstruction,
  generators: momentumGenerators,
  meta: momentumMeta,
  performance: momentumPerformance,
  flow: momentumFlow,
  scripts: momentumScripts,
};

export default momentumDefinition;

export * from "./_types";
