// File generated by 'npm run export'

import { CatsanddogsDefinition } from "./_types";

import catsanddogsAI from "./ai";
import catsanddogsAnim from "./anim";
import catsanddogsBoardBook from "./boards";
import catsanddogsSetupBook from "./setups";
import catsanddogsGraphics from "./graphics";
import catsanddogsInstruction from "./instructions";
import catsanddogsMeta from "./meta";
import catsanddogsPerformance from "./performance";
import catsanddogsFlow from "./flow";
import catsanddogsScripts from "./scripts";
import catsanddogsGenerators from "./generators";
import catsanddogsVariants from "./variants";

const catsanddogsDefinition: CatsanddogsDefinition = {
  AI: catsanddogsAI,
  anim: catsanddogsAnim,
  boards: catsanddogsBoardBook,
  setups: catsanddogsSetupBook,
  graphics: catsanddogsGraphics,
  instructions: catsanddogsInstruction,
  generators: catsanddogsGenerators,
  meta: catsanddogsMeta,
  performance: catsanddogsPerformance,
  flow: catsanddogsFlow,
  scripts: catsanddogsScripts,
  variants: catsanddogsVariants
};

export default catsanddogsDefinition;

export * from "./_types";
